from src.parser import ParsedColumnName
from src.errors import ColumnParseError

case_parse_col_name_true = [
    (
        "name",
        ParsedColumnName(
            is_valid=True,
            origin_col="name",
            field_list=["name", None, None],
            identifier=0,
            is_new=False,
        ),
    ),
    (
        "something_else",
        ParsedColumnName(
            is_valid=True,
            origin_col="something_else",
            field_list=["something_else", None, None],
            identifier=0,
            is_new=False,
        ),
    ),
    (
        "+name",
        ParsedColumnName(
            is_valid=True,
            origin_col="+name",
            field_list=["name", None, None],
            identifier=0,
            is_new=True,
        ),
    ),
    (
        "+[2]name",
        ParsedColumnName(
            is_valid=True,
            origin_col="+[2]name",
            field_list=["name", None, None],
            identifier=2,
            is_new=True,
        ),
    ),
    (
        "name:name_2",
        ParsedColumnName(
            is_valid=True,
            origin_col="name:name_2",
            field_list=["name", "name_2", None],
            identifier=0,
            is_new=False,
        ),
    ),
    (
        "[2]name:name_2",
        ParsedColumnName(
            is_valid=True,
            origin_col="[2]name:name_2",
            field_list=["name", "name_2", None],
            identifier=2,
            is_new=False,
        ),
    ),
    (
        "+[2]name:name_2",
        ParsedColumnName(
            is_valid=True,
            origin_col="+[2]name:name_2",
            field_list=["name", "name_2", None],
            identifier=2,
            is_new=True,
        ),
    ),
    (
        "name:name_2:name_3",
        ParsedColumnName(
            is_valid=True,
            origin_col="name:name_2:name_3",
            field_list=["name", "name_2", "name_3"],
            identifier=0,
            is_new=False,
        ),
    ),
    (
        "[2]name:name_2:name_3",
        ParsedColumnName(
            is_valid=True,
            origin_col="name:name_2:name_3",
            field_list=["name", "name_2", "name_3"],
            identifier=2,
            is_new=False,
        ),
    ),
    (
        "+[2]name:name_2:name_3",
        ParsedColumnName(
            is_valid=True,
            origin_col="name:name_2:name_3",
            field_list=["name", "name_2", "name_3"],
            identifier=2,
            is_new=True,
        ),
    ),
]


case_parse_col_name_false = [
    ("__", ColumnParseError),
    ("+", ColumnParseError),
    ("9s", ColumnParseError),
    ("+9s", ColumnParseError),
    ("name*", ColumnParseError),
    ("na*me", ColumnParseError),
    ("*name", ColumnParseError),
    ("name/", ColumnParseError),
    ("na/me", ColumnParseError),
    ("/name", ColumnParseError),
    ("name ", ColumnParseError),
    ("na me", ColumnParseError),
    (" name", ColumnParseError),
    ("name+", ColumnParseError),
    ("na+me", ColumnParseError),
    # ("+name", ColumnParseError),
    ("[2]name*", ColumnParseError),
    ("[2]na*me", ColumnParseError),
    ("[2]*name", ColumnParseError),
    ("[2]name/", ColumnParseError),
    ("[2]na/me", ColumnParseError),
    ("[2]/name", ColumnParseError),
    ("[2]name ", ColumnParseError),
    ("[2]na me", ColumnParseError),
    ("[2] name", ColumnParseError),
    ("[2]name+", ColumnParseError),
    ("[2]na+me", ColumnParseError),
    ("[2]+name", ColumnParseError),
    ("[]name*", ColumnParseError),
    ("[]na*me", ColumnParseError),
    ("[]*name", ColumnParseError),
    ("[]name/", ColumnParseError),
    ("[]na/me", ColumnParseError),
    ("[]/name", ColumnParseError),
    ("[]name ", ColumnParseError),
    ("[]na me", ColumnParseError),
    ("[] name", ColumnParseError),
    ("[]name+", ColumnParseError),
    ("[]na+me", ColumnParseError),
    ("[]+name", ColumnParseError),
    ("[-1]name*", ColumnParseError),
    ("[-1]na*me", ColumnParseError),
    ("[-1]*name", ColumnParseError),
    ("[-1]name/", ColumnParseError),
    ("[-1]na/me", ColumnParseError),
    ("[-1]/name", ColumnParseError),
    ("[-1]name ", ColumnParseError),
    ("[-1]na me", ColumnParseError),
    ("[-1] name", ColumnParseError),
    ("[-1]name+", ColumnParseError),
    ("[-1]na+me", ColumnParseError),
    ("[-1]+name", ColumnParseError),
    ("[abc]name*", ColumnParseError),
    ("[abc]na*me", ColumnParseError),
    ("[abc]*name", ColumnParseError),
    ("[abc]name/", ColumnParseError),
    ("[abc]na/me", ColumnParseError),
    ("[abc]/name", ColumnParseError),
    ("[abc]name ", ColumnParseError),
    ("[abc]na me", ColumnParseError),
    ("[abc] name", ColumnParseError),
    ("[abc]name+", ColumnParseError),
    ("[abc]na+me", ColumnParseError),
    ("[abc]+name", ColumnParseError),
    ("[29a]name*", ColumnParseError),
    ("[29a]na*me", ColumnParseError),
    ("[29a]*name", ColumnParseError),
    ("[29a]name/", ColumnParseError),
    ("[29a]na/me", ColumnParseError),
    ("[29a]/name", ColumnParseError),
    ("[29a]name ", ColumnParseError),
    ("[29a]na me", ColumnParseError),
    ("[29a] name", ColumnParseError),
    ("[29a]name+", ColumnParseError),
    ("[29a]na+me", ColumnParseError),
    ("[29a]+name", ColumnParseError),
    ("[2name*", ColumnParseError),
    ("[2na*me", ColumnParseError),
    ("[2*name", ColumnParseError),
    ("[2name/", ColumnParseError),
    ("[2na/me", ColumnParseError),
    ("[2/name", ColumnParseError),
    ("[2name ", ColumnParseError),
    ("[2na me", ColumnParseError),
    ("[2 name", ColumnParseError),
    ("[2name+", ColumnParseError),
    ("[2na+me", ColumnParseError),
    ("[2+name", ColumnParseError),
    ("2]name*", ColumnParseError),
    ("2]na*me", ColumnParseError),
    ("2]*name", ColumnParseError),
    ("2]name/", ColumnParseError),
    ("2]na/me", ColumnParseError),
    ("2]/name", ColumnParseError),
    ("2]name ", ColumnParseError),
    ("2]na me", ColumnParseError),
    ("2] name", ColumnParseError),
    ("2]name+", ColumnParseError),
    ("2]na+me", ColumnParseError),
    ("2]+name", ColumnParseError),
    ("[+]name*", ColumnParseError),
    ("[+]na*me", ColumnParseError),
    ("[+]*name", ColumnParseError),
    ("[+]name/", ColumnParseError),
    ("[+]na/me", ColumnParseError),
    ("[+]/name", ColumnParseError),
    ("[+]name ", ColumnParseError),
    ("[+]na me", ColumnParseError),
    ("[+] name", ColumnParseError),
    ("[+]name+", ColumnParseError),
    ("[+]na+me", ColumnParseError),
    ("[+]+name", ColumnParseError),
    ("[name*", ColumnParseError),
    ("[na*me", ColumnParseError),
    ("[*name", ColumnParseError),
    ("[name/", ColumnParseError),
    ("[na/me", ColumnParseError),
    ("[/name", ColumnParseError),
    ("[name ", ColumnParseError),
    ("[na me", ColumnParseError),
    ("[ name", ColumnParseError),
    ("[name+", ColumnParseError),
    ("[na+me", ColumnParseError),
    ("[+name", ColumnParseError),
    ("]name*", ColumnParseError),
    ("]na*me", ColumnParseError),
    ("]*name", ColumnParseError),
    ("]name/", ColumnParseError),
    ("]na/me", ColumnParseError),
    ("]/name", ColumnParseError),
    ("]name ", ColumnParseError),
    ("]na me", ColumnParseError),
    ("] name", ColumnParseError),
    ("]name+", ColumnParseError),
    ("]na+me", ColumnParseError),
    ("]+name", ColumnParseError),
    ("[ ]name*", ColumnParseError),
    ("[ ]na*me", ColumnParseError),
    ("[ ]*name", ColumnParseError),
    ("[ ]name/", ColumnParseError),
    ("[ ]na/me", ColumnParseError),
    ("[ ]/name", ColumnParseError),
    ("[ ]name ", ColumnParseError),
    ("[ ]na me", ColumnParseError),
    ("[ ] name", ColumnParseError),
    ("[ ]name+", ColumnParseError),
    ("[ ]na+me", ColumnParseError),
    ("[ ]+name", ColumnParseError),
    ("[2][name*", ColumnParseError),
    ("[2][na*me", ColumnParseError),
    ("[2][*name", ColumnParseError),
    ("[2][name/", ColumnParseError),
    ("[2][na/me", ColumnParseError),
    ("[2][/name", ColumnParseError),
    ("[2][name ", ColumnParseError),
    ("[2][na me", ColumnParseError),
    ("[2][ name", ColumnParseError),
    ("[2][name+", ColumnParseError),
    ("[2][na+me", ColumnParseError),
    ("[2][+name", ColumnParseError),
    ("[2]]name*", ColumnParseError),
    ("[2]]na*me", ColumnParseError),
    ("[2]]*name", ColumnParseError),
    ("[2]]name/", ColumnParseError),
    ("[2]]na/me", ColumnParseError),
    ("[2]]/name", ColumnParseError),
    ("[2]]name ", ColumnParseError),
    ("[2]]na me", ColumnParseError),
    ("[2]] name", ColumnParseError),
    ("[2]]name+", ColumnParseError),
    ("[2]]na+me", ColumnParseError),
    ("[2]]+name", ColumnParseError),
    ("[2][]name*", ColumnParseError),
    ("[2][]na*me", ColumnParseError),
    ("[2][]*name", ColumnParseError),
    ("[2][]name/", ColumnParseError),
    ("[2][]na/me", ColumnParseError),
    ("[2][]/name", ColumnParseError),
    ("[2][]name ", ColumnParseError),
    ("[2][]na me", ColumnParseError),
    ("[2][] name", ColumnParseError),
    ("[2][]name+", ColumnParseError),
    ("[2][]na+me", ColumnParseError),
    ("[2][]+name", ColumnParseError),
    ("[2][ ]name*", ColumnParseError),
    ("[2][ ]na*me", ColumnParseError),
    ("[2][ ]*name", ColumnParseError),
    ("[2][ ]name/", ColumnParseError),
    ("[2][ ]na/me", ColumnParseError),
    ("[2][ ]/name", ColumnParseError),
    ("[2][ ]name ", ColumnParseError),
    ("[2][ ]na me", ColumnParseError),
    ("[2][ ] name", ColumnParseError),
    ("[2][ ]name+", ColumnParseError),
    ("[2][ ]na+me", ColumnParseError),
    ("[2][ ]+name", ColumnParseError),
    ("[2][a]name*", ColumnParseError),
    ("[2][a]na*me", ColumnParseError),
    ("[2][a]*name", ColumnParseError),
    ("[2][a]name/", ColumnParseError),
    ("[2][a]na/me", ColumnParseError),
    ("[2][a]/name", ColumnParseError),
    ("[2][a]name ", ColumnParseError),
    ("[2][a]na me", ColumnParseError),
    ("[2][a] name", ColumnParseError),
    ("[2][a]name+", ColumnParseError),
    ("[2][a]na+me", ColumnParseError),
    ("[2][a]+name", ColumnParseError),
    ("[2][10]name*", ColumnParseError),
    ("[2][10]na*me", ColumnParseError),
    ("[2][10]*name", ColumnParseError),
    ("[2][10]name/", ColumnParseError),
    ("[2][10]na/me", ColumnParseError),
    ("[2][10]/name", ColumnParseError),
    ("[2][10]name ", ColumnParseError),
    ("[2][10]na me", ColumnParseError),
    ("[2][10] name", ColumnParseError),
    ("[2][10]name+", ColumnParseError),
    ("[2][10]na+me", ColumnParseError),
    ("[2][10]+name", ColumnParseError),
    ("+name*", ColumnParseError),
    ("+na*me", ColumnParseError),
    ("+*name", ColumnParseError),
    ("+name/", ColumnParseError),
    ("+na/me", ColumnParseError),
    ("+/name", ColumnParseError),
    ("+name ", ColumnParseError),
    ("+na me", ColumnParseError),
    ("+ name", ColumnParseError),
    ("+name+", ColumnParseError),
    ("+na+me", ColumnParseError),
    ("++name", ColumnParseError),
    ("+[2]name*", ColumnParseError),
    ("+[2]na*me", ColumnParseError),
    ("+[2]*name", ColumnParseError),
    ("+[2]name/", ColumnParseError),
    ("+[2]na/me", ColumnParseError),
    ("+[2]/name", ColumnParseError),
    ("+[2]name ", ColumnParseError),
    ("+[2]na me", ColumnParseError),
    ("+[2] name", ColumnParseError),
    ("+[2]name+", ColumnParseError),
    ("+[2]na+me", ColumnParseError),
    ("+[2]+name", ColumnParseError),
    ("+[]name*", ColumnParseError),
    ("+[]na*me", ColumnParseError),
    ("+[]*name", ColumnParseError),
    ("+[]name/", ColumnParseError),
    ("+[]na/me", ColumnParseError),
    ("+[]/name", ColumnParseError),
    ("+[]name ", ColumnParseError),
    ("+[]na me", ColumnParseError),
    ("+[] name", ColumnParseError),
    ("+[]name+", ColumnParseError),
    ("+[]na+me", ColumnParseError),
    ("+[]+name", ColumnParseError),
    ("+[-1]name*", ColumnParseError),
    ("+[-1]na*me", ColumnParseError),
    ("+[-1]*name", ColumnParseError),
    ("+[-1]name/", ColumnParseError),
    ("+[-1]na/me", ColumnParseError),
    ("+[-1]/name", ColumnParseError),
    ("+[-1]name ", ColumnParseError),
    ("+[-1]na me", ColumnParseError),
    ("+[-1] name", ColumnParseError),
    ("+[-1]name+", ColumnParseError),
    ("+[-1]na+me", ColumnParseError),
    ("+[-1]+name", ColumnParseError),
    ("+[abc]name*", ColumnParseError),
    ("+[abc]na*me", ColumnParseError),
    ("+[abc]*name", ColumnParseError),
    ("+[abc]name/", ColumnParseError),
    ("+[abc]na/me", ColumnParseError),
    ("+[abc]/name", ColumnParseError),
    ("+[abc]name ", ColumnParseError),
    ("+[abc]na me", ColumnParseError),
    ("+[abc] name", ColumnParseError),
    ("+[abc]name+", ColumnParseError),
    ("+[abc]na+me", ColumnParseError),
    ("+[abc]+name", ColumnParseError),
    ("+[29a]name*", ColumnParseError),
    ("+[29a]na*me", ColumnParseError),
    ("+[29a]*name", ColumnParseError),
    ("+[29a]name/", ColumnParseError),
    ("+[29a]na/me", ColumnParseError),
    ("+[29a]/name", ColumnParseError),
    ("+[29a]name ", ColumnParseError),
    ("+[29a]na me", ColumnParseError),
    ("+[29a] name", ColumnParseError),
    ("+[29a]name+", ColumnParseError),
    ("+[29a]na+me", ColumnParseError),
    ("+[29a]+name", ColumnParseError),
    ("+[2name*", ColumnParseError),
    ("+[2na*me", ColumnParseError),
    ("+[2*name", ColumnParseError),
    ("+[2name/", ColumnParseError),
    ("+[2na/me", ColumnParseError),
    ("+[2/name", ColumnParseError),
    ("+[2name ", ColumnParseError),
    ("+[2na me", ColumnParseError),
    ("+[2 name", ColumnParseError),
    ("+[2name+", ColumnParseError),
    ("+[2na+me", ColumnParseError),
    ("+[2+name", ColumnParseError),
    ("+2]name*", ColumnParseError),
    ("+2]na*me", ColumnParseError),
    ("+2]*name", ColumnParseError),
    ("+2]name/", ColumnParseError),
    ("+2]na/me", ColumnParseError),
    ("+2]/name", ColumnParseError),
    ("+2]name ", ColumnParseError),
    ("+2]na me", ColumnParseError),
    ("+2] name", ColumnParseError),
    ("+2]name+", ColumnParseError),
    ("+2]na+me", ColumnParseError),
    ("+2]+name", ColumnParseError),
    ("+[+]name*", ColumnParseError),
    ("+[+]na*me", ColumnParseError),
    ("+[+]*name", ColumnParseError),
    ("+[+]name/", ColumnParseError),
    ("+[+]na/me", ColumnParseError),
    ("+[+]/name", ColumnParseError),
    ("+[+]name ", ColumnParseError),
    ("+[+]na me", ColumnParseError),
    ("+[+] name", ColumnParseError),
    ("+[+]name+", ColumnParseError),
    ("+[+]na+me", ColumnParseError),
    ("+[+]+name", ColumnParseError),
    ("+[name*", ColumnParseError),
    ("+[na*me", ColumnParseError),
    ("+[*name", ColumnParseError),
    ("+[name/", ColumnParseError),
    ("+[na/me", ColumnParseError),
    ("+[/name", ColumnParseError),
    ("+[name ", ColumnParseError),
    ("+[na me", ColumnParseError),
    ("+[ name", ColumnParseError),
    ("+[name+", ColumnParseError),
    ("+[na+me", ColumnParseError),
    ("+[+name", ColumnParseError),
    ("+]name*", ColumnParseError),
    ("+]na*me", ColumnParseError),
    ("+]*name", ColumnParseError),
    ("+]name/", ColumnParseError),
    ("+]na/me", ColumnParseError),
    ("+]/name", ColumnParseError),
    ("+]name ", ColumnParseError),
    ("+]na me", ColumnParseError),
    ("+] name", ColumnParseError),
    ("+]name+", ColumnParseError),
    ("+]na+me", ColumnParseError),
    ("+]+name", ColumnParseError),
    ("+[ ]name*", ColumnParseError),
    ("+[ ]na*me", ColumnParseError),
    ("+[ ]*name", ColumnParseError),
    ("+[ ]name/", ColumnParseError),
    ("+[ ]na/me", ColumnParseError),
    ("+[ ]/name", ColumnParseError),
    ("+[ ]name ", ColumnParseError),
    ("+[ ]na me", ColumnParseError),
    ("+[ ] name", ColumnParseError),
    ("+[ ]name+", ColumnParseError),
    ("+[ ]na+me", ColumnParseError),
    ("+[ ]+name", ColumnParseError),
    ("+[2][name*", ColumnParseError),
    ("+[2][na*me", ColumnParseError),
    ("+[2][*name", ColumnParseError),
    ("+[2][name/", ColumnParseError),
    ("+[2][na/me", ColumnParseError),
    ("+[2][/name", ColumnParseError),
    ("+[2][name ", ColumnParseError),
    ("+[2][na me", ColumnParseError),
    ("+[2][ name", ColumnParseError),
    ("+[2][name+", ColumnParseError),
    ("+[2][na+me", ColumnParseError),
    ("+[2][+name", ColumnParseError),
    ("+[2]]name*", ColumnParseError),
    ("+[2]]na*me", ColumnParseError),
    ("+[2]]*name", ColumnParseError),
    ("+[2]]name/", ColumnParseError),
    ("+[2]]na/me", ColumnParseError),
    ("+[2]]/name", ColumnParseError),
    ("+[2]]name ", ColumnParseError),
    ("+[2]]na me", ColumnParseError),
    ("+[2]] name", ColumnParseError),
    ("+[2]]name+", ColumnParseError),
    ("+[2]]na+me", ColumnParseError),
    ("+[2]]+name", ColumnParseError),
    ("+[2][]name*", ColumnParseError),
    ("+[2][]na*me", ColumnParseError),
    ("+[2][]*name", ColumnParseError),
    ("+[2][]name/", ColumnParseError),
    ("+[2][]na/me", ColumnParseError),
    ("+[2][]/name", ColumnParseError),
    ("+[2][]name ", ColumnParseError),
    ("+[2][]na me", ColumnParseError),
    ("+[2][] name", ColumnParseError),
    ("+[2][]name+", ColumnParseError),
    ("+[2][]na+me", ColumnParseError),
    ("+[2][]+name", ColumnParseError),
    ("+[2][ ]name*", ColumnParseError),
    ("+[2][ ]na*me", ColumnParseError),
    ("+[2][ ]*name", ColumnParseError),
    ("+[2][ ]name/", ColumnParseError),
    ("+[2][ ]na/me", ColumnParseError),
    ("+[2][ ]/name", ColumnParseError),
    ("+[2][ ]name ", ColumnParseError),
    ("+[2][ ]na me", ColumnParseError),
    ("+[2][ ] name", ColumnParseError),
    ("+[2][ ]name+", ColumnParseError),
    ("+[2][ ]na+me", ColumnParseError),
    ("+[2][ ]+name", ColumnParseError),
    ("+[2][a]name*", ColumnParseError),
    ("+[2][a]na*me", ColumnParseError),
    ("+[2][a]*name", ColumnParseError),
    ("+[2][a]name/", ColumnParseError),
    ("+[2][a]na/me", ColumnParseError),
    ("+[2][a]/name", ColumnParseError),
    ("+[2][a]name ", ColumnParseError),
    ("+[2][a]na me", ColumnParseError),
    ("+[2][a] name", ColumnParseError),
    ("+[2][a]name+", ColumnParseError),
    ("+[2][a]na+me", ColumnParseError),
    ("+[2][a]+name", ColumnParseError),
    ("+[2][10]name*", ColumnParseError),
    ("+[2][10]na*me", ColumnParseError),
    ("+[2][10]*name", ColumnParseError),
    ("+[2][10]name/", ColumnParseError),
    ("+[2][10]na/me", ColumnParseError),
    ("+[2][10]/name", ColumnParseError),
    ("+[2][10]name ", ColumnParseError),
    ("+[2][10]na me", ColumnParseError),
    ("+[2][10] name", ColumnParseError),
    ("+[2][10]name+", ColumnParseError),
    ("+[2][10]na+me", ColumnParseError),
    ("+[2][10]+name", ColumnParseError),
    ("*name*", ColumnParseError),
    ("*na*me", ColumnParseError),
    ("**name", ColumnParseError),
    ("*name/", ColumnParseError),
    ("*na/me", ColumnParseError),
    ("*/name", ColumnParseError),
    ("*name ", ColumnParseError),
    ("*na me", ColumnParseError),
    ("* name", ColumnParseError),
    ("*name+", ColumnParseError),
    ("*na+me", ColumnParseError),
    ("*+name", ColumnParseError),
    ("*[2]name*", ColumnParseError),
    ("*[2]na*me", ColumnParseError),
    ("*[2]*name", ColumnParseError),
    ("*[2]name/", ColumnParseError),
    ("*[2]na/me", ColumnParseError),
    ("*[2]/name", ColumnParseError),
    ("*[2]name ", ColumnParseError),
    ("*[2]na me", ColumnParseError),
    ("*[2] name", ColumnParseError),
    ("*[2]name+", ColumnParseError),
    ("*[2]na+me", ColumnParseError),
    ("*[2]+name", ColumnParseError),
    ("*[]name*", ColumnParseError),
    ("*[]na*me", ColumnParseError),
    ("*[]*name", ColumnParseError),
    ("*[]name/", ColumnParseError),
    ("*[]na/me", ColumnParseError),
    ("*[]/name", ColumnParseError),
    ("*[]name ", ColumnParseError),
    ("*[]na me", ColumnParseError),
    ("*[] name", ColumnParseError),
    ("*[]name+", ColumnParseError),
    ("*[]na+me", ColumnParseError),
    ("*[]+name", ColumnParseError),
    ("*[-1]name*", ColumnParseError),
    ("*[-1]na*me", ColumnParseError),
    ("*[-1]*name", ColumnParseError),
    ("*[-1]name/", ColumnParseError),
    ("*[-1]na/me", ColumnParseError),
    ("*[-1]/name", ColumnParseError),
    ("*[-1]name ", ColumnParseError),
    ("*[-1]na me", ColumnParseError),
    ("*[-1] name", ColumnParseError),
    ("*[-1]name+", ColumnParseError),
    ("*[-1]na+me", ColumnParseError),
    ("*[-1]+name", ColumnParseError),
    ("*[abc]name*", ColumnParseError),
    ("*[abc]na*me", ColumnParseError),
    ("*[abc]*name", ColumnParseError),
    ("*[abc]name/", ColumnParseError),
    ("*[abc]na/me", ColumnParseError),
    ("*[abc]/name", ColumnParseError),
    ("*[abc]name ", ColumnParseError),
    ("*[abc]na me", ColumnParseError),
    ("*[abc] name", ColumnParseError),
    ("*[abc]name+", ColumnParseError),
    ("*[abc]na+me", ColumnParseError),
    ("*[abc]+name", ColumnParseError),
    ("*[29a]name*", ColumnParseError),
    ("*[29a]na*me", ColumnParseError),
    ("*[29a]*name", ColumnParseError),
    ("*[29a]name/", ColumnParseError),
    ("*[29a]na/me", ColumnParseError),
    ("*[29a]/name", ColumnParseError),
    ("*[29a]name ", ColumnParseError),
    ("*[29a]na me", ColumnParseError),
    ("*[29a] name", ColumnParseError),
    ("*[29a]name+", ColumnParseError),
    ("*[29a]na+me", ColumnParseError),
    ("*[29a]+name", ColumnParseError),
    ("*[2name*", ColumnParseError),
    ("*[2na*me", ColumnParseError),
    ("*[2*name", ColumnParseError),
    ("*[2name/", ColumnParseError),
    ("*[2na/me", ColumnParseError),
    ("*[2/name", ColumnParseError),
    ("*[2name ", ColumnParseError),
    ("*[2na me", ColumnParseError),
    ("*[2 name", ColumnParseError),
    ("*[2name+", ColumnParseError),
    ("*[2na+me", ColumnParseError),
    ("*[2+name", ColumnParseError),
    ("*2]name*", ColumnParseError),
    ("*2]na*me", ColumnParseError),
    ("*2]*name", ColumnParseError),
    ("*2]name/", ColumnParseError),
    ("*2]na/me", ColumnParseError),
    ("*2]/name", ColumnParseError),
    ("*2]name ", ColumnParseError),
    ("*2]na me", ColumnParseError),
    ("*2] name", ColumnParseError),
    ("*2]name+", ColumnParseError),
    ("*2]na+me", ColumnParseError),
    ("*2]+name", ColumnParseError),
    ("*[+]name*", ColumnParseError),
    ("*[+]na*me", ColumnParseError),
    ("*[+]*name", ColumnParseError),
    ("*[+]name/", ColumnParseError),
    ("*[+]na/me", ColumnParseError),
    ("*[+]/name", ColumnParseError),
    ("*[+]name ", ColumnParseError),
    ("*[+]na me", ColumnParseError),
    ("*[+] name", ColumnParseError),
    ("*[+]name+", ColumnParseError),
    ("*[+]na+me", ColumnParseError),
    ("*[+]+name", ColumnParseError),
    ("*[name*", ColumnParseError),
    ("*[na*me", ColumnParseError),
    ("*[*name", ColumnParseError),
    ("*[name/", ColumnParseError),
    ("*[na/me", ColumnParseError),
    ("*[/name", ColumnParseError),
    ("*[name ", ColumnParseError),
    ("*[na me", ColumnParseError),
    ("*[ name", ColumnParseError),
    ("*[name+", ColumnParseError),
    ("*[na+me", ColumnParseError),
    ("*[+name", ColumnParseError),
    ("*]name*", ColumnParseError),
    ("*]na*me", ColumnParseError),
    ("*]*name", ColumnParseError),
    ("*]name/", ColumnParseError),
    ("*]na/me", ColumnParseError),
    ("*]/name", ColumnParseError),
    ("*]name ", ColumnParseError),
    ("*]na me", ColumnParseError),
    ("*] name", ColumnParseError),
    ("*]name+", ColumnParseError),
    ("*]na+me", ColumnParseError),
    ("*]+name", ColumnParseError),
    ("*[ ]name*", ColumnParseError),
    ("*[ ]na*me", ColumnParseError),
    ("*[ ]*name", ColumnParseError),
    ("*[ ]name/", ColumnParseError),
    ("*[ ]na/me", ColumnParseError),
    ("*[ ]/name", ColumnParseError),
    ("*[ ]name ", ColumnParseError),
    ("*[ ]na me", ColumnParseError),
    ("*[ ] name", ColumnParseError),
    ("*[ ]name+", ColumnParseError),
    ("*[ ]na+me", ColumnParseError),
    ("*[ ]+name", ColumnParseError),
    ("*[2][name*", ColumnParseError),
    ("*[2][na*me", ColumnParseError),
    ("*[2][*name", ColumnParseError),
    ("*[2][name/", ColumnParseError),
    ("*[2][na/me", ColumnParseError),
    ("*[2][/name", ColumnParseError),
    ("*[2][name ", ColumnParseError),
    ("*[2][na me", ColumnParseError),
    ("*[2][ name", ColumnParseError),
    ("*[2][name+", ColumnParseError),
    ("*[2][na+me", ColumnParseError),
    ("*[2][+name", ColumnParseError),
    ("*[2]]name*", ColumnParseError),
    ("*[2]]na*me", ColumnParseError),
    ("*[2]]*name", ColumnParseError),
    ("*[2]]name/", ColumnParseError),
    ("*[2]]na/me", ColumnParseError),
    ("*[2]]/name", ColumnParseError),
    ("*[2]]name ", ColumnParseError),
    ("*[2]]na me", ColumnParseError),
    ("*[2]] name", ColumnParseError),
    ("*[2]]name+", ColumnParseError),
    ("*[2]]na+me", ColumnParseError),
    ("*[2]]+name", ColumnParseError),
    ("*[2][]name*", ColumnParseError),
    ("*[2][]na*me", ColumnParseError),
    ("*[2][]*name", ColumnParseError),
    ("*[2][]name/", ColumnParseError),
    ("*[2][]na/me", ColumnParseError),
    ("*[2][]/name", ColumnParseError),
    ("*[2][]name ", ColumnParseError),
    ("*[2][]na me", ColumnParseError),
    ("*[2][] name", ColumnParseError),
    ("*[2][]name+", ColumnParseError),
    ("*[2][]na+me", ColumnParseError),
    ("*[2][]+name", ColumnParseError),
    ("*[2][ ]name*", ColumnParseError),
    ("*[2][ ]na*me", ColumnParseError),
    ("*[2][ ]*name", ColumnParseError),
    ("*[2][ ]name/", ColumnParseError),
    ("*[2][ ]na/me", ColumnParseError),
    ("*[2][ ]/name", ColumnParseError),
    ("*[2][ ]name ", ColumnParseError),
    ("*[2][ ]na me", ColumnParseError),
    ("*[2][ ] name", ColumnParseError),
    ("*[2][ ]name+", ColumnParseError),
    ("*[2][ ]na+me", ColumnParseError),
    ("*[2][ ]+name", ColumnParseError),
    ("*[2][a]name*", ColumnParseError),
    ("*[2][a]na*me", ColumnParseError),
    ("*[2][a]*name", ColumnParseError),
    ("*[2][a]name/", ColumnParseError),
    ("*[2][a]na/me", ColumnParseError),
    ("*[2][a]/name", ColumnParseError),
    ("*[2][a]name ", ColumnParseError),
    ("*[2][a]na me", ColumnParseError),
    ("*[2][a] name", ColumnParseError),
    ("*[2][a]name+", ColumnParseError),
    ("*[2][a]na+me", ColumnParseError),
    ("*[2][a]+name", ColumnParseError),
    ("*[2][10]name*", ColumnParseError),
    ("*[2][10]na*me", ColumnParseError),
    ("*[2][10]*name", ColumnParseError),
    ("*[2][10]name/", ColumnParseError),
    ("*[2][10]na/me", ColumnParseError),
    ("*[2][10]/name", ColumnParseError),
    ("*[2][10]name ", ColumnParseError),
    ("*[2][10]na me", ColumnParseError),
    ("*[2][10] name", ColumnParseError),
    ("*[2][10]name+", ColumnParseError),
    ("*[2][10]na+me", ColumnParseError),
    ("*[2][10]+name", ColumnParseError),
    ("+name*:name_2", ColumnParseError),
    ("+na*me:name_2", ColumnParseError),
    ("+*name:name_2", ColumnParseError),
    ("+name/:name_2", ColumnParseError),
    ("+na/me:name_2", ColumnParseError),
    ("+/name:name_2", ColumnParseError),
    ("+name :name_2", ColumnParseError),
    ("+na me:name_2", ColumnParseError),
    ("+ name:name_2", ColumnParseError),
    ("+name+:name_2", ColumnParseError),
    ("+na+me:name_2", ColumnParseError),
    ("++name:name_2", ColumnParseError),
    ("+[2]name*:name_2", ColumnParseError),
    ("+[2]na*me:name_2", ColumnParseError),
    ("+[2]*name:name_2", ColumnParseError),
    ("+[2]name/:name_2", ColumnParseError),
    ("+[2]na/me:name_2", ColumnParseError),
    ("+[2]/name:name_2", ColumnParseError),
    ("+[2]name :name_2", ColumnParseError),
    ("+[2]na me:name_2", ColumnParseError),
    ("+[2] name:name_2", ColumnParseError),
    ("+[2]name+:name_2", ColumnParseError),
    ("+[2]na+me:name_2", ColumnParseError),
    ("+[2]+name:name_2", ColumnParseError),
    ("+[]name*:name_2", ColumnParseError),
    ("+[]na*me:name_2", ColumnParseError),
    ("+[]*name:name_2", ColumnParseError),
    ("+[]name/:name_2", ColumnParseError),
    ("+[]na/me:name_2", ColumnParseError),
    ("+[]/name:name_2", ColumnParseError),
    ("+[]name :name_2", ColumnParseError),
    ("+[]na me:name_2", ColumnParseError),
    ("+[] name:name_2", ColumnParseError),
    ("+[]name+:name_2", ColumnParseError),
    ("+[]na+me:name_2", ColumnParseError),
    ("+[]+name:name_2", ColumnParseError),
    ("+[-1]name*:name_2", ColumnParseError),
    ("+[-1]na*me:name_2", ColumnParseError),
    ("+[-1]*name:name_2", ColumnParseError),
    ("+[-1]name/:name_2", ColumnParseError),
    ("+[-1]na/me:name_2", ColumnParseError),
    ("+[-1]/name:name_2", ColumnParseError),
    ("+[-1]name :name_2", ColumnParseError),
    ("+[-1]na me:name_2", ColumnParseError),
    ("+[-1] name:name_2", ColumnParseError),
    ("+[-1]name+:name_2", ColumnParseError),
    ("+[-1]na+me:name_2", ColumnParseError),
    ("+[-1]+name:name_2", ColumnParseError),
    ("+[abc]name*:name_2", ColumnParseError),
    ("+[abc]na*me:name_2", ColumnParseError),
    ("+[abc]*name:name_2", ColumnParseError),
    ("+[abc]name/:name_2", ColumnParseError),
    ("+[abc]na/me:name_2", ColumnParseError),
    ("+[abc]/name:name_2", ColumnParseError),
    ("+[abc]name :name_2", ColumnParseError),
    ("+[abc]na me:name_2", ColumnParseError),
    ("+[abc] name:name_2", ColumnParseError),
    ("+[abc]name+:name_2", ColumnParseError),
    ("+[abc]na+me:name_2", ColumnParseError),
    ("+[abc]+name:name_2", ColumnParseError),
    ("+[29a]name*:name_2", ColumnParseError),
    ("+[29a]na*me:name_2", ColumnParseError),
    ("+[29a]*name:name_2", ColumnParseError),
    ("+[29a]name/:name_2", ColumnParseError),
    ("+[29a]na/me:name_2", ColumnParseError),
    ("+[29a]/name:name_2", ColumnParseError),
    ("+[29a]name :name_2", ColumnParseError),
    ("+[29a]na me:name_2", ColumnParseError),
    ("+[29a] name:name_2", ColumnParseError),
    ("+[29a]name+:name_2", ColumnParseError),
    ("+[29a]na+me:name_2", ColumnParseError),
    ("+[29a]+name:name_2", ColumnParseError),
    ("+[2name*:name_2", ColumnParseError),
    ("+[2na*me:name_2", ColumnParseError),
    ("+[2*name:name_2", ColumnParseError),
    ("+[2name/:name_2", ColumnParseError),
    ("+[2na/me:name_2", ColumnParseError),
    ("+[2/name:name_2", ColumnParseError),
    ("+[2name :name_2", ColumnParseError),
    ("+[2na me:name_2", ColumnParseError),
    ("+[2 name:name_2", ColumnParseError),
    ("+[2name+:name_2", ColumnParseError),
    ("+[2na+me:name_2", ColumnParseError),
    ("+[2+name:name_2", ColumnParseError),
    ("+2]name*:name_2", ColumnParseError),
    ("+2]na*me:name_2", ColumnParseError),
    ("+2]*name:name_2", ColumnParseError),
    ("+2]name/:name_2", ColumnParseError),
    ("+2]na/me:name_2", ColumnParseError),
    ("+2]/name:name_2", ColumnParseError),
    ("+2]name :name_2", ColumnParseError),
    ("+2]na me:name_2", ColumnParseError),
    ("+2] name:name_2", ColumnParseError),
    ("+2]name+:name_2", ColumnParseError),
    ("+2]na+me:name_2", ColumnParseError),
    ("+2]+name:name_2", ColumnParseError),
    ("+[+]name*:name_2", ColumnParseError),
    ("+[+]na*me:name_2", ColumnParseError),
    ("+[+]*name:name_2", ColumnParseError),
    ("+[+]name/:name_2", ColumnParseError),
    ("+[+]na/me:name_2", ColumnParseError),
    ("+[+]/name:name_2", ColumnParseError),
    ("+[+]name :name_2", ColumnParseError),
    ("+[+]na me:name_2", ColumnParseError),
    ("+[+] name:name_2", ColumnParseError),
    ("+[+]name+:name_2", ColumnParseError),
    ("+[+]na+me:name_2", ColumnParseError),
    ("+[+]+name:name_2", ColumnParseError),
    ("+[name*:name_2", ColumnParseError),
    ("+[na*me:name_2", ColumnParseError),
    ("+[*name:name_2", ColumnParseError),
    ("+[name/:name_2", ColumnParseError),
    ("+[na/me:name_2", ColumnParseError),
    ("+[/name:name_2", ColumnParseError),
    ("+[name :name_2", ColumnParseError),
    ("+[na me:name_2", ColumnParseError),
    ("+[ name:name_2", ColumnParseError),
    ("+[name+:name_2", ColumnParseError),
    ("+[na+me:name_2", ColumnParseError),
    ("+[+name:name_2", ColumnParseError),
    ("+]name*:name_2", ColumnParseError),
    ("+]na*me:name_2", ColumnParseError),
    ("+]*name:name_2", ColumnParseError),
    ("+]name/:name_2", ColumnParseError),
    ("+]na/me:name_2", ColumnParseError),
    ("+]/name:name_2", ColumnParseError),
    ("+]name :name_2", ColumnParseError),
    ("+]na me:name_2", ColumnParseError),
    ("+] name:name_2", ColumnParseError),
    ("+]name+:name_2", ColumnParseError),
    ("+]na+me:name_2", ColumnParseError),
    ("+]+name:name_2", ColumnParseError),
    ("+[ ]name*:name_2", ColumnParseError),
    ("+[ ]na*me:name_2", ColumnParseError),
    ("+[ ]*name:name_2", ColumnParseError),
    ("+[ ]name/:name_2", ColumnParseError),
    ("+[ ]na/me:name_2", ColumnParseError),
    ("+[ ]/name:name_2", ColumnParseError),
    ("+[ ]name :name_2", ColumnParseError),
    ("+[ ]na me:name_2", ColumnParseError),
    ("+[ ] name:name_2", ColumnParseError),
    ("+[ ]name+:name_2", ColumnParseError),
    ("+[ ]na+me:name_2", ColumnParseError),
    ("+[ ]+name:name_2", ColumnParseError),
    ("+[2][name*:name_2", ColumnParseError),
    ("+[2][na*me:name_2", ColumnParseError),
    ("+[2][*name:name_2", ColumnParseError),
    ("+[2][name/:name_2", ColumnParseError),
    ("+[2][na/me:name_2", ColumnParseError),
    ("+[2][/name:name_2", ColumnParseError),
    ("+[2][name :name_2", ColumnParseError),
    ("+[2][na me:name_2", ColumnParseError),
    ("+[2][ name:name_2", ColumnParseError),
    ("+[2][name+:name_2", ColumnParseError),
    ("+[2][na+me:name_2", ColumnParseError),
    ("+[2][+name:name_2", ColumnParseError),
    ("+[2]]name*:name_2", ColumnParseError),
    ("+[2]]na*me:name_2", ColumnParseError),
    ("+[2]]*name:name_2", ColumnParseError),
    ("+[2]]name/:name_2", ColumnParseError),
    ("+[2]]na/me:name_2", ColumnParseError),
    ("+[2]]/name:name_2", ColumnParseError),
    ("+[2]]name :name_2", ColumnParseError),
    ("+[2]]na me:name_2", ColumnParseError),
    ("+[2]] name:name_2", ColumnParseError),
    ("+[2]]name+:name_2", ColumnParseError),
    ("+[2]]na+me:name_2", ColumnParseError),
    ("+[2]]+name:name_2", ColumnParseError),
    ("+[2][]name*:name_2", ColumnParseError),
    ("+[2][]na*me:name_2", ColumnParseError),
    ("+[2][]*name:name_2", ColumnParseError),
    ("+[2][]name/:name_2", ColumnParseError),
    ("+[2][]na/me:name_2", ColumnParseError),
    ("+[2][]/name:name_2", ColumnParseError),
    ("+[2][]name :name_2", ColumnParseError),
    ("+[2][]na me:name_2", ColumnParseError),
    ("+[2][] name:name_2", ColumnParseError),
    ("+[2][]name+:name_2", ColumnParseError),
    ("+[2][]na+me:name_2", ColumnParseError),
    ("+[2][]+name:name_2", ColumnParseError),
    ("+[2][ ]name*:name_2", ColumnParseError),
    ("+[2][ ]na*me:name_2", ColumnParseError),
    ("+[2][ ]*name:name_2", ColumnParseError),
    ("+[2][ ]name/:name_2", ColumnParseError),
    ("+[2][ ]na/me:name_2", ColumnParseError),
    ("+[2][ ]/name:name_2", ColumnParseError),
    ("+[2][ ]name :name_2", ColumnParseError),
    ("+[2][ ]na me:name_2", ColumnParseError),
    ("+[2][ ] name:name_2", ColumnParseError),
    ("+[2][ ]name+:name_2", ColumnParseError),
    ("+[2][ ]na+me:name_2", ColumnParseError),
    ("+[2][ ]+name:name_2", ColumnParseError),
    ("+[2][a]name*:name_2", ColumnParseError),
    ("+[2][a]na*me:name_2", ColumnParseError),
    ("+[2][a]*name:name_2", ColumnParseError),
    ("+[2][a]name/:name_2", ColumnParseError),
    ("+[2][a]na/me:name_2", ColumnParseError),
    ("+[2][a]/name:name_2", ColumnParseError),
    ("+[2][a]name :name_2", ColumnParseError),
    ("+[2][a]na me:name_2", ColumnParseError),
    ("+[2][a] name:name_2", ColumnParseError),
    ("+[2][a]name+:name_2", ColumnParseError),
    ("+[2][a]na+me:name_2", ColumnParseError),
    ("+[2][a]+name:name_2", ColumnParseError),
    ("+[2][10]name*:name_2", ColumnParseError),
    ("+[2][10]na*me:name_2", ColumnParseError),
    ("+[2][10]*name:name_2", ColumnParseError),
    ("+[2][10]name/:name_2", ColumnParseError),
    ("+[2][10]na/me:name_2", ColumnParseError),
    ("+[2][10]/name:name_2", ColumnParseError),
    ("+[2][10]name :name_2", ColumnParseError),
    ("+[2][10]na me:name_2", ColumnParseError),
    ("+[2][10] name:name_2", ColumnParseError),
    ("+[2][10]name+:name_2", ColumnParseError),
    ("+[2][10]na+me:name_2", ColumnParseError),
    ("+[2][10]+name:name_2", ColumnParseError),
    ("name*:name_2", ColumnParseError),
    ("na*me:name_2", ColumnParseError),
    ("*name:name_2", ColumnParseError),
    ("name/:name_2", ColumnParseError),
    ("na/me:name_2", ColumnParseError),
    ("/name:name_2", ColumnParseError),
    ("name :name_2", ColumnParseError),
    ("na me:name_2", ColumnParseError),
    (" name:name_2", ColumnParseError),
    ("name+:name_2", ColumnParseError),
    ("na+me:name_2", ColumnParseError),
    # ("+name:name_2", ColumnParseError),
    ("[2]name*:name_2", ColumnParseError),
    ("[2]na*me:name_2", ColumnParseError),
    ("[2]*name:name_2", ColumnParseError),
    ("[2]name/:name_2", ColumnParseError),
    ("[2]na/me:name_2", ColumnParseError),
    ("[2]/name:name_2", ColumnParseError),
    ("[2]name :name_2", ColumnParseError),
    ("[2]na me:name_2", ColumnParseError),
    ("[2] name:name_2", ColumnParseError),
    ("[2]name+:name_2", ColumnParseError),
    ("[2]na+me:name_2", ColumnParseError),
    ("[2]+name:name_2", ColumnParseError),
    ("[]name*:name_2", ColumnParseError),
    ("[]na*me:name_2", ColumnParseError),
    ("[]*name:name_2", ColumnParseError),
    ("[]name/:name_2", ColumnParseError),
    ("[]na/me:name_2", ColumnParseError),
    ("[]/name:name_2", ColumnParseError),
    ("[]name :name_2", ColumnParseError),
    ("[]na me:name_2", ColumnParseError),
    ("[] name:name_2", ColumnParseError),
    ("[]name+:name_2", ColumnParseError),
    ("[]na+me:name_2", ColumnParseError),
    ("[]+name:name_2", ColumnParseError),
    ("[-1]name*:name_2", ColumnParseError),
    ("[-1]na*me:name_2", ColumnParseError),
    ("[-1]*name:name_2", ColumnParseError),
    ("[-1]name/:name_2", ColumnParseError),
    ("[-1]na/me:name_2", ColumnParseError),
    ("[-1]/name:name_2", ColumnParseError),
    ("[-1]name :name_2", ColumnParseError),
    ("[-1]na me:name_2", ColumnParseError),
    ("[-1] name:name_2", ColumnParseError),
    ("[-1]name+:name_2", ColumnParseError),
    ("[-1]na+me:name_2", ColumnParseError),
    ("[-1]+name:name_2", ColumnParseError),
    ("[abc]name*:name_2", ColumnParseError),
    ("[abc]na*me:name_2", ColumnParseError),
    ("[abc]*name:name_2", ColumnParseError),
    ("[abc]name/:name_2", ColumnParseError),
    ("[abc]na/me:name_2", ColumnParseError),
    ("[abc]/name:name_2", ColumnParseError),
    ("[abc]name :name_2", ColumnParseError),
    ("[abc]na me:name_2", ColumnParseError),
    ("[abc] name:name_2", ColumnParseError),
    ("[abc]name+:name_2", ColumnParseError),
    ("[abc]na+me:name_2", ColumnParseError),
    ("[abc]+name:name_2", ColumnParseError),
    ("[29a]name*:name_2", ColumnParseError),
    ("[29a]na*me:name_2", ColumnParseError),
    ("[29a]*name:name_2", ColumnParseError),
    ("[29a]name/:name_2", ColumnParseError),
    ("[29a]na/me:name_2", ColumnParseError),
    ("[29a]/name:name_2", ColumnParseError),
    ("[29a]name :name_2", ColumnParseError),
    ("[29a]na me:name_2", ColumnParseError),
    ("[29a] name:name_2", ColumnParseError),
    ("[29a]name+:name_2", ColumnParseError),
    ("[29a]na+me:name_2", ColumnParseError),
    ("[29a]+name:name_2", ColumnParseError),
    ("[2name*:name_2", ColumnParseError),
    ("[2na*me:name_2", ColumnParseError),
    ("[2*name:name_2", ColumnParseError),
    ("[2name/:name_2", ColumnParseError),
    ("[2na/me:name_2", ColumnParseError),
    ("[2/name:name_2", ColumnParseError),
    ("[2name :name_2", ColumnParseError),
    ("[2na me:name_2", ColumnParseError),
    ("[2 name:name_2", ColumnParseError),
    ("[2name+:name_2", ColumnParseError),
    ("[2na+me:name_2", ColumnParseError),
    ("[2+name:name_2", ColumnParseError),
    ("2]name*:name_2", ColumnParseError),
    ("2]na*me:name_2", ColumnParseError),
    ("2]*name:name_2", ColumnParseError),
    ("2]name/:name_2", ColumnParseError),
    ("2]na/me:name_2", ColumnParseError),
    ("2]/name:name_2", ColumnParseError),
    ("2]name :name_2", ColumnParseError),
    ("2]na me:name_2", ColumnParseError),
    ("2] name:name_2", ColumnParseError),
    ("2]name+:name_2", ColumnParseError),
    ("2]na+me:name_2", ColumnParseError),
    ("2]+name:name_2", ColumnParseError),
    ("[+]name*:name_2", ColumnParseError),
    ("[+]na*me:name_2", ColumnParseError),
    ("[+]*name:name_2", ColumnParseError),
    ("[+]name/:name_2", ColumnParseError),
    ("[+]na/me:name_2", ColumnParseError),
    ("[+]/name:name_2", ColumnParseError),
    ("[+]name :name_2", ColumnParseError),
    ("[+]na me:name_2", ColumnParseError),
    ("[+] name:name_2", ColumnParseError),
    ("[+]name+:name_2", ColumnParseError),
    ("[+]na+me:name_2", ColumnParseError),
    ("[+]+name:name_2", ColumnParseError),
    ("[name*:name_2", ColumnParseError),
    ("[na*me:name_2", ColumnParseError),
    ("[*name:name_2", ColumnParseError),
    ("[name/:name_2", ColumnParseError),
    ("[na/me:name_2", ColumnParseError),
    ("[/name:name_2", ColumnParseError),
    ("[name :name_2", ColumnParseError),
    ("[na me:name_2", ColumnParseError),
    ("[ name:name_2", ColumnParseError),
    ("[name+:name_2", ColumnParseError),
    ("[na+me:name_2", ColumnParseError),
    ("[+name:name_2", ColumnParseError),
    ("]name*:name_2", ColumnParseError),
    ("]na*me:name_2", ColumnParseError),
    ("]*name:name_2", ColumnParseError),
    ("]name/:name_2", ColumnParseError),
    ("]na/me:name_2", ColumnParseError),
    ("]/name:name_2", ColumnParseError),
    ("]name :name_2", ColumnParseError),
    ("]na me:name_2", ColumnParseError),
    ("] name:name_2", ColumnParseError),
    ("]name+:name_2", ColumnParseError),
    ("]na+me:name_2", ColumnParseError),
    ("]+name:name_2", ColumnParseError),
    ("[ ]name*:name_2", ColumnParseError),
    ("[ ]na*me:name_2", ColumnParseError),
    ("[ ]*name:name_2", ColumnParseError),
    ("[ ]name/:name_2", ColumnParseError),
    ("[ ]na/me:name_2", ColumnParseError),
    ("[ ]/name:name_2", ColumnParseError),
    ("[ ]name :name_2", ColumnParseError),
    ("[ ]na me:name_2", ColumnParseError),
    ("[ ] name:name_2", ColumnParseError),
    ("[ ]name+:name_2", ColumnParseError),
    ("[ ]na+me:name_2", ColumnParseError),
    ("[ ]+name:name_2", ColumnParseError),
    ("[2][name*:name_2", ColumnParseError),
    ("[2][na*me:name_2", ColumnParseError),
    ("[2][*name:name_2", ColumnParseError),
    ("[2][name/:name_2", ColumnParseError),
    ("[2][na/me:name_2", ColumnParseError),
    ("[2][/name:name_2", ColumnParseError),
    ("[2][name :name_2", ColumnParseError),
    ("[2][na me:name_2", ColumnParseError),
    ("[2][ name:name_2", ColumnParseError),
    ("[2][name+:name_2", ColumnParseError),
    ("[2][na+me:name_2", ColumnParseError),
    ("[2][+name:name_2", ColumnParseError),
    ("[2]]name*:name_2", ColumnParseError),
    ("[2]]na*me:name_2", ColumnParseError),
    ("[2]]*name:name_2", ColumnParseError),
    ("[2]]name/:name_2", ColumnParseError),
    ("[2]]na/me:name_2", ColumnParseError),
    ("[2]]/name:name_2", ColumnParseError),
    ("[2]]name :name_2", ColumnParseError),
    ("[2]]na me:name_2", ColumnParseError),
    ("[2]] name:name_2", ColumnParseError),
    ("[2]]name+:name_2", ColumnParseError),
    ("[2]]na+me:name_2", ColumnParseError),
    ("[2]]+name:name_2", ColumnParseError),
    ("[2][]name*:name_2", ColumnParseError),
    ("[2][]na*me:name_2", ColumnParseError),
    ("[2][]*name:name_2", ColumnParseError),
    ("[2][]name/:name_2", ColumnParseError),
    ("[2][]na/me:name_2", ColumnParseError),
    ("[2][]/name:name_2", ColumnParseError),
    ("[2][]name :name_2", ColumnParseError),
    ("[2][]na me:name_2", ColumnParseError),
    ("[2][] name:name_2", ColumnParseError),
    ("[2][]name+:name_2", ColumnParseError),
    ("[2][]na+me:name_2", ColumnParseError),
    ("[2][]+name:name_2", ColumnParseError),
    ("[2][ ]name*:name_2", ColumnParseError),
    ("[2][ ]na*me:name_2", ColumnParseError),
    ("[2][ ]*name:name_2", ColumnParseError),
    ("[2][ ]name/:name_2", ColumnParseError),
    ("[2][ ]na/me:name_2", ColumnParseError),
    ("[2][ ]/name:name_2", ColumnParseError),
    ("[2][ ]name :name_2", ColumnParseError),
    ("[2][ ]na me:name_2", ColumnParseError),
    ("[2][ ] name:name_2", ColumnParseError),
    ("[2][ ]name+:name_2", ColumnParseError),
    ("[2][ ]na+me:name_2", ColumnParseError),
    ("[2][ ]+name:name_2", ColumnParseError),
    ("[2][a]name*:name_2", ColumnParseError),
    ("[2][a]na*me:name_2", ColumnParseError),
    ("[2][a]*name:name_2", ColumnParseError),
    ("[2][a]name/:name_2", ColumnParseError),
    ("[2][a]na/me:name_2", ColumnParseError),
    ("[2][a]/name:name_2", ColumnParseError),
    ("[2][a]name :name_2", ColumnParseError),
    ("[2][a]na me:name_2", ColumnParseError),
    ("[2][a] name:name_2", ColumnParseError),
    ("[2][a]name+:name_2", ColumnParseError),
    ("[2][a]na+me:name_2", ColumnParseError),
    ("[2][a]+name:name_2", ColumnParseError),
    ("[2][10]name*:name_2", ColumnParseError),
    ("[2][10]na*me:name_2", ColumnParseError),
    ("[2][10]*name:name_2", ColumnParseError),
    ("[2][10]name/:name_2", ColumnParseError),
    ("[2][10]na/me:name_2", ColumnParseError),
    ("[2][10]/name:name_2", ColumnParseError),
    ("[2][10]name :name_2", ColumnParseError),
    ("[2][10]na me:name_2", ColumnParseError),
    ("[2][10] name:name_2", ColumnParseError),
    ("[2][10]name+:name_2", ColumnParseError),
    ("[2][10]na+me:name_2", ColumnParseError),
    ("[2][10]+name:name_2", ColumnParseError),
    ("+name*:name_2:name_3", ColumnParseError),
    ("+na*me:name_2:name_3", ColumnParseError),
    ("+*name:name_2:name_3", ColumnParseError),
    ("+name/:name_2:name_3", ColumnParseError),
    ("+na/me:name_2:name_3", ColumnParseError),
    ("+/name:name_2:name_3", ColumnParseError),
    ("+name :name_2:name_3", ColumnParseError),
    ("+na me:name_2:name_3", ColumnParseError),
    ("+ name:name_2:name_3", ColumnParseError),
    ("+name+:name_2:name_3", ColumnParseError),
    ("+na+me:name_2:name_3", ColumnParseError),
    ("++name:name_2:name_3", ColumnParseError),
    ("+[2]name*:name_2:name_3", ColumnParseError),
    ("+[2]na*me:name_2:name_3", ColumnParseError),
    ("+[2]*name:name_2:name_3", ColumnParseError),
    ("+[2]name/:name_2:name_3", ColumnParseError),
    ("+[2]na/me:name_2:name_3", ColumnParseError),
    ("+[2]/name:name_2:name_3", ColumnParseError),
    ("+[2]name :name_2:name_3", ColumnParseError),
    ("+[2]na me:name_2:name_3", ColumnParseError),
    ("+[2] name:name_2:name_3", ColumnParseError),
    ("+[2]name+:name_2:name_3", ColumnParseError),
    ("+[2]na+me:name_2:name_3", ColumnParseError),
    ("+[2]+name:name_2:name_3", ColumnParseError),
    ("+[]name*:name_2:name_3", ColumnParseError),
    ("+[]na*me:name_2:name_3", ColumnParseError),
    ("+[]*name:name_2:name_3", ColumnParseError),
    ("+[]name/:name_2:name_3", ColumnParseError),
    ("+[]na/me:name_2:name_3", ColumnParseError),
    ("+[]/name:name_2:name_3", ColumnParseError),
    ("+[]name :name_2:name_3", ColumnParseError),
    ("+[]na me:name_2:name_3", ColumnParseError),
    ("+[] name:name_2:name_3", ColumnParseError),
    ("+[]name+:name_2:name_3", ColumnParseError),
    ("+[]na+me:name_2:name_3", ColumnParseError),
    ("+[]+name:name_2:name_3", ColumnParseError),
    ("+[-1]name*:name_2:name_3", ColumnParseError),
    ("+[-1]na*me:name_2:name_3", ColumnParseError),
    ("+[-1]*name:name_2:name_3", ColumnParseError),
    ("+[-1]name/:name_2:name_3", ColumnParseError),
    ("+[-1]na/me:name_2:name_3", ColumnParseError),
    ("+[-1]/name:name_2:name_3", ColumnParseError),
    ("+[-1]name :name_2:name_3", ColumnParseError),
    ("+[-1]na me:name_2:name_3", ColumnParseError),
    ("+[-1] name:name_2:name_3", ColumnParseError),
    ("+[-1]name+:name_2:name_3", ColumnParseError),
    ("+[-1]na+me:name_2:name_3", ColumnParseError),
    ("+[-1]+name:name_2:name_3", ColumnParseError),
    ("+[abc]name*:name_2:name_3", ColumnParseError),
    ("+[abc]na*me:name_2:name_3", ColumnParseError),
    ("+[abc]*name:name_2:name_3", ColumnParseError),
    ("+[abc]name/:name_2:name_3", ColumnParseError),
    ("+[abc]na/me:name_2:name_3", ColumnParseError),
    ("+[abc]/name:name_2:name_3", ColumnParseError),
    ("+[abc]name :name_2:name_3", ColumnParseError),
    ("+[abc]na me:name_2:name_3", ColumnParseError),
    ("+[abc] name:name_2:name_3", ColumnParseError),
    ("+[abc]name+:name_2:name_3", ColumnParseError),
    ("+[abc]na+me:name_2:name_3", ColumnParseError),
    ("+[abc]+name:name_2:name_3", ColumnParseError),
    ("+[29a]name*:name_2:name_3", ColumnParseError),
    ("+[29a]na*me:name_2:name_3", ColumnParseError),
    ("+[29a]*name:name_2:name_3", ColumnParseError),
    ("+[29a]name/:name_2:name_3", ColumnParseError),
    ("+[29a]na/me:name_2:name_3", ColumnParseError),
    ("+[29a]/name:name_2:name_3", ColumnParseError),
    ("+[29a]name :name_2:name_3", ColumnParseError),
    ("+[29a]na me:name_2:name_3", ColumnParseError),
    ("+[29a] name:name_2:name_3", ColumnParseError),
    ("+[29a]name+:name_2:name_3", ColumnParseError),
    ("+[29a]na+me:name_2:name_3", ColumnParseError),
    ("+[29a]+name:name_2:name_3", ColumnParseError),
    ("+[2name*:name_2:name_3", ColumnParseError),
    ("+[2na*me:name_2:name_3", ColumnParseError),
    ("+[2*name:name_2:name_3", ColumnParseError),
    ("+[2name/:name_2:name_3", ColumnParseError),
    ("+[2na/me:name_2:name_3", ColumnParseError),
    ("+[2/name:name_2:name_3", ColumnParseError),
    ("+[2name :name_2:name_3", ColumnParseError),
    ("+[2na me:name_2:name_3", ColumnParseError),
    ("+[2 name:name_2:name_3", ColumnParseError),
    ("+[2name+:name_2:name_3", ColumnParseError),
    ("+[2na+me:name_2:name_3", ColumnParseError),
    ("+[2+name:name_2:name_3", ColumnParseError),
    ("+2]name*:name_2:name_3", ColumnParseError),
    ("+2]na*me:name_2:name_3", ColumnParseError),
    ("+2]*name:name_2:name_3", ColumnParseError),
    ("+2]name/:name_2:name_3", ColumnParseError),
    ("+2]na/me:name_2:name_3", ColumnParseError),
    ("+2]/name:name_2:name_3", ColumnParseError),
    ("+2]name :name_2:name_3", ColumnParseError),
    ("+2]na me:name_2:name_3", ColumnParseError),
    ("+2] name:name_2:name_3", ColumnParseError),
    ("+2]name+:name_2:name_3", ColumnParseError),
    ("+2]na+me:name_2:name_3", ColumnParseError),
    ("+2]+name:name_2:name_3", ColumnParseError),
    ("+[+]name*:name_2:name_3", ColumnParseError),
    ("+[+]na*me:name_2:name_3", ColumnParseError),
    ("+[+]*name:name_2:name_3", ColumnParseError),
    ("+[+]name/:name_2:name_3", ColumnParseError),
    ("+[+]na/me:name_2:name_3", ColumnParseError),
    ("+[+]/name:name_2:name_3", ColumnParseError),
    ("+[+]name :name_2:name_3", ColumnParseError),
    ("+[+]na me:name_2:name_3", ColumnParseError),
    ("+[+] name:name_2:name_3", ColumnParseError),
    ("+[+]name+:name_2:name_3", ColumnParseError),
    ("+[+]na+me:name_2:name_3", ColumnParseError),
    ("+[+]+name:name_2:name_3", ColumnParseError),
    ("+[name*:name_2:name_3", ColumnParseError),
    ("+[na*me:name_2:name_3", ColumnParseError),
    ("+[*name:name_2:name_3", ColumnParseError),
    ("+[name/:name_2:name_3", ColumnParseError),
    ("+[na/me:name_2:name_3", ColumnParseError),
    ("+[/name:name_2:name_3", ColumnParseError),
    ("+[name :name_2:name_3", ColumnParseError),
    ("+[na me:name_2:name_3", ColumnParseError),
    ("+[ name:name_2:name_3", ColumnParseError),
    ("+[name+:name_2:name_3", ColumnParseError),
    ("+[na+me:name_2:name_3", ColumnParseError),
    ("+[+name:name_2:name_3", ColumnParseError),
    ("+]name*:name_2:name_3", ColumnParseError),
    ("+]na*me:name_2:name_3", ColumnParseError),
    ("+]*name:name_2:name_3", ColumnParseError),
    ("+]name/:name_2:name_3", ColumnParseError),
    ("+]na/me:name_2:name_3", ColumnParseError),
    ("+]/name:name_2:name_3", ColumnParseError),
    ("+]name :name_2:name_3", ColumnParseError),
    ("+]na me:name_2:name_3", ColumnParseError),
    ("+] name:name_2:name_3", ColumnParseError),
    ("+]name+:name_2:name_3", ColumnParseError),
    ("+]na+me:name_2:name_3", ColumnParseError),
    ("+]+name:name_2:name_3", ColumnParseError),
    ("+[ ]name*:name_2:name_3", ColumnParseError),
    ("+[ ]na*me:name_2:name_3", ColumnParseError),
    ("+[ ]*name:name_2:name_3", ColumnParseError),
    ("+[ ]name/:name_2:name_3", ColumnParseError),
    ("+[ ]na/me:name_2:name_3", ColumnParseError),
    ("+[ ]/name:name_2:name_3", ColumnParseError),
    ("+[ ]name :name_2:name_3", ColumnParseError),
    ("+[ ]na me:name_2:name_3", ColumnParseError),
    ("+[ ] name:name_2:name_3", ColumnParseError),
    ("+[ ]name+:name_2:name_3", ColumnParseError),
    ("+[ ]na+me:name_2:name_3", ColumnParseError),
    ("+[ ]+name:name_2:name_3", ColumnParseError),
    ("+[2][name*:name_2:name_3", ColumnParseError),
    ("+[2][na*me:name_2:name_3", ColumnParseError),
    ("+[2][*name:name_2:name_3", ColumnParseError),
    ("+[2][name/:name_2:name_3", ColumnParseError),
    ("+[2][na/me:name_2:name_3", ColumnParseError),
    ("+[2][/name:name_2:name_3", ColumnParseError),
    ("+[2][name :name_2:name_3", ColumnParseError),
    ("+[2][na me:name_2:name_3", ColumnParseError),
    ("+[2][ name:name_2:name_3", ColumnParseError),
    ("+[2][name+:name_2:name_3", ColumnParseError),
    ("+[2][na+me:name_2:name_3", ColumnParseError),
    ("+[2][+name:name_2:name_3", ColumnParseError),
    ("+[2]]name*:name_2:name_3", ColumnParseError),
    ("+[2]]na*me:name_2:name_3", ColumnParseError),
    ("+[2]]*name:name_2:name_3", ColumnParseError),
    ("+[2]]name/:name_2:name_3", ColumnParseError),
    ("+[2]]na/me:name_2:name_3", ColumnParseError),
    ("+[2]]/name:name_2:name_3", ColumnParseError),
    ("+[2]]name :name_2:name_3", ColumnParseError),
    ("+[2]]na me:name_2:name_3", ColumnParseError),
    ("+[2]] name:name_2:name_3", ColumnParseError),
    ("+[2]]name+:name_2:name_3", ColumnParseError),
    ("+[2]]na+me:name_2:name_3", ColumnParseError),
    ("+[2]]+name:name_2:name_3", ColumnParseError),
    ("+[2][]name*:name_2:name_3", ColumnParseError),
    ("+[2][]na*me:name_2:name_3", ColumnParseError),
    ("+[2][]*name:name_2:name_3", ColumnParseError),
    ("+[2][]name/:name_2:name_3", ColumnParseError),
    ("+[2][]na/me:name_2:name_3", ColumnParseError),
    ("+[2][]/name:name_2:name_3", ColumnParseError),
    ("+[2][]name :name_2:name_3", ColumnParseError),
    ("+[2][]na me:name_2:name_3", ColumnParseError),
    ("+[2][] name:name_2:name_3", ColumnParseError),
    ("+[2][]name+:name_2:name_3", ColumnParseError),
    ("+[2][]na+me:name_2:name_3", ColumnParseError),
    ("+[2][]+name:name_2:name_3", ColumnParseError),
    ("+[2][ ]name*:name_2:name_3", ColumnParseError),
    ("+[2][ ]na*me:name_2:name_3", ColumnParseError),
    ("+[2][ ]*name:name_2:name_3", ColumnParseError),
    ("+[2][ ]name/:name_2:name_3", ColumnParseError),
    ("+[2][ ]na/me:name_2:name_3", ColumnParseError),
    ("+[2][ ]/name:name_2:name_3", ColumnParseError),
    ("+[2][ ]name :name_2:name_3", ColumnParseError),
    ("+[2][ ]na me:name_2:name_3", ColumnParseError),
    ("+[2][ ] name:name_2:name_3", ColumnParseError),
    ("+[2][ ]name+:name_2:name_3", ColumnParseError),
    ("+[2][ ]na+me:name_2:name_3", ColumnParseError),
    ("+[2][ ]+name:name_2:name_3", ColumnParseError),
    ("+[2][a]name*:name_2:name_3", ColumnParseError),
    ("+[2][a]na*me:name_2:name_3", ColumnParseError),
    ("+[2][a]*name:name_2:name_3", ColumnParseError),
    ("+[2][a]name/:name_2:name_3", ColumnParseError),
    ("+[2][a]na/me:name_2:name_3", ColumnParseError),
    ("+[2][a]/name:name_2:name_3", ColumnParseError),
    ("+[2][a]name :name_2:name_3", ColumnParseError),
    ("+[2][a]na me:name_2:name_3", ColumnParseError),
    ("+[2][a] name:name_2:name_3", ColumnParseError),
    ("+[2][a]name+:name_2:name_3", ColumnParseError),
    ("+[2][a]na+me:name_2:name_3", ColumnParseError),
    ("+[2][a]+name:name_2:name_3", ColumnParseError),
    ("+[2][10]name*:name_2:name_3", ColumnParseError),
    ("+[2][10]na*me:name_2:name_3", ColumnParseError),
    ("+[2][10]*name:name_2:name_3", ColumnParseError),
    ("+[2][10]name/:name_2:name_3", ColumnParseError),
    ("+[2][10]na/me:name_2:name_3", ColumnParseError),
    ("+[2][10]/name:name_2:name_3", ColumnParseError),
    ("+[2][10]name :name_2:name_3", ColumnParseError),
    ("+[2][10]na me:name_2:name_3", ColumnParseError),
    ("+[2][10] name:name_2:name_3", ColumnParseError),
    ("+[2][10]name+:name_2:name_3", ColumnParseError),
    ("+[2][10]na+me:name_2:name_3", ColumnParseError),
    ("+[2][10]+name:name_2:name_3", ColumnParseError),
    ("name*:name_2:name_3", ColumnParseError),
    ("na*me:name_2:name_3", ColumnParseError),
    ("*name:name_2:name_3", ColumnParseError),
    ("name/:name_2:name_3", ColumnParseError),
    ("na/me:name_2:name_3", ColumnParseError),
    ("/name:name_2:name_3", ColumnParseError),
    ("name :name_2:name_3", ColumnParseError),
    ("na me:name_2:name_3", ColumnParseError),
    (" name:name_2:name_3", ColumnParseError),
    ("name+:name_2:name_3", ColumnParseError),
    ("na+me:name_2:name_3", ColumnParseError),
    # ("+name:name_2:name_3", ColumnParseError),
    ("[2]name*:name_2:name_3", ColumnParseError),
    ("[2]na*me:name_2:name_3", ColumnParseError),
    ("[2]*name:name_2:name_3", ColumnParseError),
    ("[2]name/:name_2:name_3", ColumnParseError),
    ("[2]na/me:name_2:name_3", ColumnParseError),
    ("[2]/name:name_2:name_3", ColumnParseError),
    ("[2]name :name_2:name_3", ColumnParseError),
    ("[2]na me:name_2:name_3", ColumnParseError),
    ("[2] name:name_2:name_3", ColumnParseError),
    ("[2]name+:name_2:name_3", ColumnParseError),
    ("[2]na+me:name_2:name_3", ColumnParseError),
    ("[2]+name:name_2:name_3", ColumnParseError),
    ("[]name*:name_2:name_3", ColumnParseError),
    ("[]na*me:name_2:name_3", ColumnParseError),
    ("[]*name:name_2:name_3", ColumnParseError),
    ("[]name/:name_2:name_3", ColumnParseError),
    ("[]na/me:name_2:name_3", ColumnParseError),
    ("[]/name:name_2:name_3", ColumnParseError),
    ("[]name :name_2:name_3", ColumnParseError),
    ("[]na me:name_2:name_3", ColumnParseError),
    ("[] name:name_2:name_3", ColumnParseError),
    ("[]name+:name_2:name_3", ColumnParseError),
    ("[]na+me:name_2:name_3", ColumnParseError),
    ("[]+name:name_2:name_3", ColumnParseError),
    ("[-1]name*:name_2:name_3", ColumnParseError),
    ("[-1]na*me:name_2:name_3", ColumnParseError),
    ("[-1]*name:name_2:name_3", ColumnParseError),
    ("[-1]name/:name_2:name_3", ColumnParseError),
    ("[-1]na/me:name_2:name_3", ColumnParseError),
    ("[-1]/name:name_2:name_3", ColumnParseError),
    ("[-1]name :name_2:name_3", ColumnParseError),
    ("[-1]na me:name_2:name_3", ColumnParseError),
    ("[-1] name:name_2:name_3", ColumnParseError),
    ("[-1]name+:name_2:name_3", ColumnParseError),
    ("[-1]na+me:name_2:name_3", ColumnParseError),
    ("[-1]+name:name_2:name_3", ColumnParseError),
    ("[abc]name*:name_2:name_3", ColumnParseError),
    ("[abc]na*me:name_2:name_3", ColumnParseError),
    ("[abc]*name:name_2:name_3", ColumnParseError),
    ("[abc]name/:name_2:name_3", ColumnParseError),
    ("[abc]na/me:name_2:name_3", ColumnParseError),
    ("[abc]/name:name_2:name_3", ColumnParseError),
    ("[abc]name :name_2:name_3", ColumnParseError),
    ("[abc]na me:name_2:name_3", ColumnParseError),
    ("[abc] name:name_2:name_3", ColumnParseError),
    ("[abc]name+:name_2:name_3", ColumnParseError),
    ("[abc]na+me:name_2:name_3", ColumnParseError),
    ("[abc]+name:name_2:name_3", ColumnParseError),
    ("[29a]name*:name_2:name_3", ColumnParseError),
    ("[29a]na*me:name_2:name_3", ColumnParseError),
    ("[29a]*name:name_2:name_3", ColumnParseError),
    ("[29a]name/:name_2:name_3", ColumnParseError),
    ("[29a]na/me:name_2:name_3", ColumnParseError),
    ("[29a]/name:name_2:name_3", ColumnParseError),
    ("[29a]name :name_2:name_3", ColumnParseError),
    ("[29a]na me:name_2:name_3", ColumnParseError),
    ("[29a] name:name_2:name_3", ColumnParseError),
    ("[29a]name+:name_2:name_3", ColumnParseError),
    ("[29a]na+me:name_2:name_3", ColumnParseError),
    ("[29a]+name:name_2:name_3", ColumnParseError),
    ("[2name*:name_2:name_3", ColumnParseError),
    ("[2na*me:name_2:name_3", ColumnParseError),
    ("[2*name:name_2:name_3", ColumnParseError),
    ("[2name/:name_2:name_3", ColumnParseError),
    ("[2na/me:name_2:name_3", ColumnParseError),
    ("[2/name:name_2:name_3", ColumnParseError),
    ("[2name :name_2:name_3", ColumnParseError),
    ("[2na me:name_2:name_3", ColumnParseError),
    ("[2 name:name_2:name_3", ColumnParseError),
    ("[2name+:name_2:name_3", ColumnParseError),
    ("[2na+me:name_2:name_3", ColumnParseError),
    ("[2+name:name_2:name_3", ColumnParseError),
    ("2]name*:name_2:name_3", ColumnParseError),
    ("2]na*me:name_2:name_3", ColumnParseError),
    ("2]*name:name_2:name_3", ColumnParseError),
    ("2]name/:name_2:name_3", ColumnParseError),
    ("2]na/me:name_2:name_3", ColumnParseError),
    ("2]/name:name_2:name_3", ColumnParseError),
    ("2]name :name_2:name_3", ColumnParseError),
    ("2]na me:name_2:name_3", ColumnParseError),
    ("2] name:name_2:name_3", ColumnParseError),
    ("2]name+:name_2:name_3", ColumnParseError),
    ("2]na+me:name_2:name_3", ColumnParseError),
    ("2]+name:name_2:name_3", ColumnParseError),
    ("[+]name*:name_2:name_3", ColumnParseError),
    ("[+]na*me:name_2:name_3", ColumnParseError),
    ("[+]*name:name_2:name_3", ColumnParseError),
    ("[+]name/:name_2:name_3", ColumnParseError),
    ("[+]na/me:name_2:name_3", ColumnParseError),
    ("[+]/name:name_2:name_3", ColumnParseError),
    ("[+]name :name_2:name_3", ColumnParseError),
    ("[+]na me:name_2:name_3", ColumnParseError),
    ("[+] name:name_2:name_3", ColumnParseError),
    ("[+]name+:name_2:name_3", ColumnParseError),
    ("[+]na+me:name_2:name_3", ColumnParseError),
    ("[+]+name:name_2:name_3", ColumnParseError),
    ("[name*:name_2:name_3", ColumnParseError),
    ("[na*me:name_2:name_3", ColumnParseError),
    ("[*name:name_2:name_3", ColumnParseError),
    ("[name/:name_2:name_3", ColumnParseError),
    ("[na/me:name_2:name_3", ColumnParseError),
    ("[/name:name_2:name_3", ColumnParseError),
    ("[name :name_2:name_3", ColumnParseError),
    ("[na me:name_2:name_3", ColumnParseError),
    ("[ name:name_2:name_3", ColumnParseError),
    ("[name+:name_2:name_3", ColumnParseError),
    ("[na+me:name_2:name_3", ColumnParseError),
    ("[+name:name_2:name_3", ColumnParseError),
    ("]name*:name_2:name_3", ColumnParseError),
    ("]na*me:name_2:name_3", ColumnParseError),
    ("]*name:name_2:name_3", ColumnParseError),
    ("]name/:name_2:name_3", ColumnParseError),
    ("]na/me:name_2:name_3", ColumnParseError),
    ("]/name:name_2:name_3", ColumnParseError),
    ("]name :name_2:name_3", ColumnParseError),
    ("]na me:name_2:name_3", ColumnParseError),
    ("] name:name_2:name_3", ColumnParseError),
    ("]name+:name_2:name_3", ColumnParseError),
    ("]na+me:name_2:name_3", ColumnParseError),
    ("]+name:name_2:name_3", ColumnParseError),
    ("[ ]name*:name_2:name_3", ColumnParseError),
    ("[ ]na*me:name_2:name_3", ColumnParseError),
    ("[ ]*name:name_2:name_3", ColumnParseError),
    ("[ ]name/:name_2:name_3", ColumnParseError),
    ("[ ]na/me:name_2:name_3", ColumnParseError),
    ("[ ]/name:name_2:name_3", ColumnParseError),
    ("[ ]name :name_2:name_3", ColumnParseError),
    ("[ ]na me:name_2:name_3", ColumnParseError),
    ("[ ] name:name_2:name_3", ColumnParseError),
    ("[ ]name+:name_2:name_3", ColumnParseError),
    ("[ ]na+me:name_2:name_3", ColumnParseError),
    ("[ ]+name:name_2:name_3", ColumnParseError),
    ("[2][name*:name_2:name_3", ColumnParseError),
    ("[2][na*me:name_2:name_3", ColumnParseError),
    ("[2][*name:name_2:name_3", ColumnParseError),
    ("[2][name/:name_2:name_3", ColumnParseError),
    ("[2][na/me:name_2:name_3", ColumnParseError),
    ("[2][/name:name_2:name_3", ColumnParseError),
    ("[2][name :name_2:name_3", ColumnParseError),
    ("[2][na me:name_2:name_3", ColumnParseError),
    ("[2][ name:name_2:name_3", ColumnParseError),
    ("[2][name+:name_2:name_3", ColumnParseError),
    ("[2][na+me:name_2:name_3", ColumnParseError),
    ("[2][+name:name_2:name_3", ColumnParseError),
    ("[2]]name*:name_2:name_3", ColumnParseError),
    ("[2]]na*me:name_2:name_3", ColumnParseError),
    ("[2]]*name:name_2:name_3", ColumnParseError),
    ("[2]]name/:name_2:name_3", ColumnParseError),
    ("[2]]na/me:name_2:name_3", ColumnParseError),
    ("[2]]/name:name_2:name_3", ColumnParseError),
    ("[2]]name :name_2:name_3", ColumnParseError),
    ("[2]]na me:name_2:name_3", ColumnParseError),
    ("[2]] name:name_2:name_3", ColumnParseError),
    ("[2]]name+:name_2:name_3", ColumnParseError),
    ("[2]]na+me:name_2:name_3", ColumnParseError),
    ("[2]]+name:name_2:name_3", ColumnParseError),
    ("[2][]name*:name_2:name_3", ColumnParseError),
    ("[2][]na*me:name_2:name_3", ColumnParseError),
    ("[2][]*name:name_2:name_3", ColumnParseError),
    ("[2][]name/:name_2:name_3", ColumnParseError),
    ("[2][]na/me:name_2:name_3", ColumnParseError),
    ("[2][]/name:name_2:name_3", ColumnParseError),
    ("[2][]name :name_2:name_3", ColumnParseError),
    ("[2][]na me:name_2:name_3", ColumnParseError),
    ("[2][] name:name_2:name_3", ColumnParseError),
    ("[2][]name+:name_2:name_3", ColumnParseError),
    ("[2][]na+me:name_2:name_3", ColumnParseError),
    ("[2][]+name:name_2:name_3", ColumnParseError),
    ("[2][ ]name*:name_2:name_3", ColumnParseError),
    ("[2][ ]na*me:name_2:name_3", ColumnParseError),
    ("[2][ ]*name:name_2:name_3", ColumnParseError),
    ("[2][ ]name/:name_2:name_3", ColumnParseError),
    ("[2][ ]na/me:name_2:name_3", ColumnParseError),
    ("[2][ ]/name:name_2:name_3", ColumnParseError),
    ("[2][ ]name :name_2:name_3", ColumnParseError),
    ("[2][ ]na me:name_2:name_3", ColumnParseError),
    ("[2][ ] name:name_2:name_3", ColumnParseError),
    ("[2][ ]name+:name_2:name_3", ColumnParseError),
    ("[2][ ]na+me:name_2:name_3", ColumnParseError),
    ("[2][ ]+name:name_2:name_3", ColumnParseError),
    ("[2][a]name*:name_2:name_3", ColumnParseError),
    ("[2][a]na*me:name_2:name_3", ColumnParseError),
    ("[2][a]*name:name_2:name_3", ColumnParseError),
    ("[2][a]name/:name_2:name_3", ColumnParseError),
    ("[2][a]na/me:name_2:name_3", ColumnParseError),
    ("[2][a]/name:name_2:name_3", ColumnParseError),
    ("[2][a]name :name_2:name_3", ColumnParseError),
    ("[2][a]na me:name_2:name_3", ColumnParseError),
    ("[2][a] name:name_2:name_3", ColumnParseError),
    ("[2][a]name+:name_2:name_3", ColumnParseError),
    ("[2][a]na+me:name_2:name_3", ColumnParseError),
    ("[2][a]+name:name_2:name_3", ColumnParseError),
    ("[2][10]name*:name_2:name_3", ColumnParseError),
    ("[2][10]na*me:name_2:name_3", ColumnParseError),
    ("[2][10]*name:name_2:name_3", ColumnParseError),
    ("[2][10]name/:name_2:name_3", ColumnParseError),
    ("[2][10]na/me:name_2:name_3", ColumnParseError),
    ("[2][10]/name:name_2:name_3", ColumnParseError),
    ("[2][10]name :name_2:name_3", ColumnParseError),
    ("[2][10]na me:name_2:name_3", ColumnParseError),
    ("[2][10] name:name_2:name_3", ColumnParseError),
    ("[2][10]name+:name_2:name_3", ColumnParseError),
    ("[2][10]na+me:name_2:name_3", ColumnParseError),
    ("[2][10]+name:name_2:name_3", ColumnParseError),
    ("+name*:name_2:name_3:name_4", ColumnParseError),
    ("+na*me:name_2:name_3:name_4", ColumnParseError),
    ("+*name:name_2:name_3:name_4", ColumnParseError),
    ("+name/:name_2:name_3:name_4", ColumnParseError),
    ("+na/me:name_2:name_3:name_4", ColumnParseError),
    ("+/name:name_2:name_3:name_4", ColumnParseError),
    ("+name :name_2:name_3:name_4", ColumnParseError),
    ("+na me:name_2:name_3:name_4", ColumnParseError),
    ("+ name:name_2:name_3:name_4", ColumnParseError),
    ("+name+:name_2:name_3:name_4", ColumnParseError),
    ("+na+me:name_2:name_3:name_4", ColumnParseError),
    ("++name:name_2:name_3:name_4", ColumnParseError),
    ("+[2]name*:name_2:name_3:name_4", ColumnParseError),
    ("+[2]na*me:name_2:name_3:name_4", ColumnParseError),
    ("+[2]*name:name_2:name_3:name_4", ColumnParseError),
    ("+[2]name/:name_2:name_3:name_4", ColumnParseError),
    ("+[2]na/me:name_2:name_3:name_4", ColumnParseError),
    ("+[2]/name:name_2:name_3:name_4", ColumnParseError),
    ("+[2]name :name_2:name_3:name_4", ColumnParseError),
    ("+[2]na me:name_2:name_3:name_4", ColumnParseError),
    ("+[2] name:name_2:name_3:name_4", ColumnParseError),
    ("+[2]name+:name_2:name_3:name_4", ColumnParseError),
    ("+[2]na+me:name_2:name_3:name_4", ColumnParseError),
    ("+[2]+name:name_2:name_3:name_4", ColumnParseError),
    ("+[]name*:name_2:name_3:name_4", ColumnParseError),
    ("+[]na*me:name_2:name_3:name_4", ColumnParseError),
    ("+[]*name:name_2:name_3:name_4", ColumnParseError),
    ("+[]name/:name_2:name_3:name_4", ColumnParseError),
    ("+[]na/me:name_2:name_3:name_4", ColumnParseError),
    ("+[]/name:name_2:name_3:name_4", ColumnParseError),
    ("+[]name :name_2:name_3:name_4", ColumnParseError),
    ("+[]na me:name_2:name_3:name_4", ColumnParseError),
    ("+[] name:name_2:name_3:name_4", ColumnParseError),
    ("+[]name+:name_2:name_3:name_4", ColumnParseError),
    ("+[]na+me:name_2:name_3:name_4", ColumnParseError),
    ("+[]+name:name_2:name_3:name_4", ColumnParseError),
    ("+[-1]name*:name_2:name_3:name_4", ColumnParseError),
    ("+[-1]na*me:name_2:name_3:name_4", ColumnParseError),
    ("+[-1]*name:name_2:name_3:name_4", ColumnParseError),
    ("+[-1]name/:name_2:name_3:name_4", ColumnParseError),
    ("+[-1]na/me:name_2:name_3:name_4", ColumnParseError),
    ("+[-1]/name:name_2:name_3:name_4", ColumnParseError),
    ("+[-1]name :name_2:name_3:name_4", ColumnParseError),
    ("+[-1]na me:name_2:name_3:name_4", ColumnParseError),
    ("+[-1] name:name_2:name_3:name_4", ColumnParseError),
    ("+[-1]name+:name_2:name_3:name_4", ColumnParseError),
    ("+[-1]na+me:name_2:name_3:name_4", ColumnParseError),
    ("+[-1]+name:name_2:name_3:name_4", ColumnParseError),
    ("+[abc]name*:name_2:name_3:name_4", ColumnParseError),
    ("+[abc]na*me:name_2:name_3:name_4", ColumnParseError),
    ("+[abc]*name:name_2:name_3:name_4", ColumnParseError),
    ("+[abc]name/:name_2:name_3:name_4", ColumnParseError),
    ("+[abc]na/me:name_2:name_3:name_4", ColumnParseError),
    ("+[abc]/name:name_2:name_3:name_4", ColumnParseError),
    ("+[abc]name :name_2:name_3:name_4", ColumnParseError),
    ("+[abc]na me:name_2:name_3:name_4", ColumnParseError),
    ("+[abc] name:name_2:name_3:name_4", ColumnParseError),
    ("+[abc]name+:name_2:name_3:name_4", ColumnParseError),
    ("+[abc]na+me:name_2:name_3:name_4", ColumnParseError),
    ("+[abc]+name:name_2:name_3:name_4", ColumnParseError),
    ("+[29a]name*:name_2:name_3:name_4", ColumnParseError),
    ("+[29a]na*me:name_2:name_3:name_4", ColumnParseError),
    ("+[29a]*name:name_2:name_3:name_4", ColumnParseError),
    ("+[29a]name/:name_2:name_3:name_4", ColumnParseError),
    ("+[29a]na/me:name_2:name_3:name_4", ColumnParseError),
    ("+[29a]/name:name_2:name_3:name_4", ColumnParseError),
    ("+[29a]name :name_2:name_3:name_4", ColumnParseError),
    ("+[29a]na me:name_2:name_3:name_4", ColumnParseError),
    ("+[29a] name:name_2:name_3:name_4", ColumnParseError),
    ("+[29a]name+:name_2:name_3:name_4", ColumnParseError),
    ("+[29a]na+me:name_2:name_3:name_4", ColumnParseError),
    ("+[29a]+name:name_2:name_3:name_4", ColumnParseError),
    ("+[2name*:name_2:name_3:name_4", ColumnParseError),
    ("+[2na*me:name_2:name_3:name_4", ColumnParseError),
    ("+[2*name:name_2:name_3:name_4", ColumnParseError),
    ("+[2name/:name_2:name_3:name_4", ColumnParseError),
    ("+[2na/me:name_2:name_3:name_4", ColumnParseError),
    ("+[2/name:name_2:name_3:name_4", ColumnParseError),
    ("+[2name :name_2:name_3:name_4", ColumnParseError),
    ("+[2na me:name_2:name_3:name_4", ColumnParseError),
    ("+[2 name:name_2:name_3:name_4", ColumnParseError),
    ("+[2name+:name_2:name_3:name_4", ColumnParseError),
    ("+[2na+me:name_2:name_3:name_4", ColumnParseError),
    ("+[2+name:name_2:name_3:name_4", ColumnParseError),
    ("+2]name*:name_2:name_3:name_4", ColumnParseError),
    ("+2]na*me:name_2:name_3:name_4", ColumnParseError),
    ("+2]*name:name_2:name_3:name_4", ColumnParseError),
    ("+2]name/:name_2:name_3:name_4", ColumnParseError),
    ("+2]na/me:name_2:name_3:name_4", ColumnParseError),
    ("+2]/name:name_2:name_3:name_4", ColumnParseError),
    ("+2]name :name_2:name_3:name_4", ColumnParseError),
    ("+2]na me:name_2:name_3:name_4", ColumnParseError),
    ("+2] name:name_2:name_3:name_4", ColumnParseError),
    ("+2]name+:name_2:name_3:name_4", ColumnParseError),
    ("+2]na+me:name_2:name_3:name_4", ColumnParseError),
    ("+2]+name:name_2:name_3:name_4", ColumnParseError),
    ("+[+]name*:name_2:name_3:name_4", ColumnParseError),
    ("+[+]na*me:name_2:name_3:name_4", ColumnParseError),
    ("+[+]*name:name_2:name_3:name_4", ColumnParseError),
    ("+[+]name/:name_2:name_3:name_4", ColumnParseError),
    ("+[+]na/me:name_2:name_3:name_4", ColumnParseError),
    ("+[+]/name:name_2:name_3:name_4", ColumnParseError),
    ("+[+]name :name_2:name_3:name_4", ColumnParseError),
    ("+[+]na me:name_2:name_3:name_4", ColumnParseError),
    ("+[+] name:name_2:name_3:name_4", ColumnParseError),
    ("+[+]name+:name_2:name_3:name_4", ColumnParseError),
    ("+[+]na+me:name_2:name_3:name_4", ColumnParseError),
    ("+[+]+name:name_2:name_3:name_4", ColumnParseError),
    ("+[name*:name_2:name_3:name_4", ColumnParseError),
    ("+[na*me:name_2:name_3:name_4", ColumnParseError),
    ("+[*name:name_2:name_3:name_4", ColumnParseError),
    ("+[name/:name_2:name_3:name_4", ColumnParseError),
    ("+[na/me:name_2:name_3:name_4", ColumnParseError),
    ("+[/name:name_2:name_3:name_4", ColumnParseError),
    ("+[name :name_2:name_3:name_4", ColumnParseError),
    ("+[na me:name_2:name_3:name_4", ColumnParseError),
    ("+[ name:name_2:name_3:name_4", ColumnParseError),
    ("+[name+:name_2:name_3:name_4", ColumnParseError),
    ("+[na+me:name_2:name_3:name_4", ColumnParseError),
    ("+[+name:name_2:name_3:name_4", ColumnParseError),
    ("+]name*:name_2:name_3:name_4", ColumnParseError),
    ("+]na*me:name_2:name_3:name_4", ColumnParseError),
    ("+]*name:name_2:name_3:name_4", ColumnParseError),
    ("+]name/:name_2:name_3:name_4", ColumnParseError),
    ("+]na/me:name_2:name_3:name_4", ColumnParseError),
    ("+]/name:name_2:name_3:name_4", ColumnParseError),
    ("+]name :name_2:name_3:name_4", ColumnParseError),
    ("+]na me:name_2:name_3:name_4", ColumnParseError),
    ("+] name:name_2:name_3:name_4", ColumnParseError),
    ("+]name+:name_2:name_3:name_4", ColumnParseError),
    ("+]na+me:name_2:name_3:name_4", ColumnParseError),
    ("+]+name:name_2:name_3:name_4", ColumnParseError),
    ("+[ ]name*:name_2:name_3:name_4", ColumnParseError),
    ("+[ ]na*me:name_2:name_3:name_4", ColumnParseError),
    ("+[ ]*name:name_2:name_3:name_4", ColumnParseError),
    ("+[ ]name/:name_2:name_3:name_4", ColumnParseError),
    ("+[ ]na/me:name_2:name_3:name_4", ColumnParseError),
    ("+[ ]/name:name_2:name_3:name_4", ColumnParseError),
    ("+[ ]name :name_2:name_3:name_4", ColumnParseError),
    ("+[ ]na me:name_2:name_3:name_4", ColumnParseError),
    ("+[ ] name:name_2:name_3:name_4", ColumnParseError),
    ("+[ ]name+:name_2:name_3:name_4", ColumnParseError),
    ("+[ ]na+me:name_2:name_3:name_4", ColumnParseError),
    ("+[ ]+name:name_2:name_3:name_4", ColumnParseError),
    ("+[2][name*:name_2:name_3:name_4", ColumnParseError),
    ("+[2][na*me:name_2:name_3:name_4", ColumnParseError),
    ("+[2][*name:name_2:name_3:name_4", ColumnParseError),
    ("+[2][name/:name_2:name_3:name_4", ColumnParseError),
    ("+[2][na/me:name_2:name_3:name_4", ColumnParseError),
    ("+[2][/name:name_2:name_3:name_4", ColumnParseError),
    ("+[2][name :name_2:name_3:name_4", ColumnParseError),
    ("+[2][na me:name_2:name_3:name_4", ColumnParseError),
    ("+[2][ name:name_2:name_3:name_4", ColumnParseError),
    ("+[2][name+:name_2:name_3:name_4", ColumnParseError),
    ("+[2][na+me:name_2:name_3:name_4", ColumnParseError),
    ("+[2][+name:name_2:name_3:name_4", ColumnParseError),
    ("+[2]]name*:name_2:name_3:name_4", ColumnParseError),
    ("+[2]]na*me:name_2:name_3:name_4", ColumnParseError),
    ("+[2]]*name:name_2:name_3:name_4", ColumnParseError),
    ("+[2]]name/:name_2:name_3:name_4", ColumnParseError),
    ("+[2]]na/me:name_2:name_3:name_4", ColumnParseError),
    ("+[2]]/name:name_2:name_3:name_4", ColumnParseError),
    ("+[2]]name :name_2:name_3:name_4", ColumnParseError),
    ("+[2]]na me:name_2:name_3:name_4", ColumnParseError),
    ("+[2]] name:name_2:name_3:name_4", ColumnParseError),
    ("+[2]]name+:name_2:name_3:name_4", ColumnParseError),
    ("+[2]]na+me:name_2:name_3:name_4", ColumnParseError),
    ("+[2]]+name:name_2:name_3:name_4", ColumnParseError),
    ("+[2][]name*:name_2:name_3:name_4", ColumnParseError),
    ("+[2][]na*me:name_2:name_3:name_4", ColumnParseError),
    ("+[2][]*name:name_2:name_3:name_4", ColumnParseError),
    ("+[2][]name/:name_2:name_3:name_4", ColumnParseError),
    ("+[2][]na/me:name_2:name_3:name_4", ColumnParseError),
    ("+[2][]/name:name_2:name_3:name_4", ColumnParseError),
    ("+[2][]name :name_2:name_3:name_4", ColumnParseError),
    ("+[2][]na me:name_2:name_3:name_4", ColumnParseError),
    ("+[2][] name:name_2:name_3:name_4", ColumnParseError),
    ("+[2][]name+:name_2:name_3:name_4", ColumnParseError),
    ("+[2][]na+me:name_2:name_3:name_4", ColumnParseError),
    ("+[2][]+name:name_2:name_3:name_4", ColumnParseError),
    ("+[2][ ]name*:name_2:name_3:name_4", ColumnParseError),
    ("+[2][ ]na*me:name_2:name_3:name_4", ColumnParseError),
    ("+[2][ ]*name:name_2:name_3:name_4", ColumnParseError),
    ("+[2][ ]name/:name_2:name_3:name_4", ColumnParseError),
    ("+[2][ ]na/me:name_2:name_3:name_4", ColumnParseError),
    ("+[2][ ]/name:name_2:name_3:name_4", ColumnParseError),
    ("+[2][ ]name :name_2:name_3:name_4", ColumnParseError),
    ("+[2][ ]na me:name_2:name_3:name_4", ColumnParseError),
    ("+[2][ ] name:name_2:name_3:name_4", ColumnParseError),
    ("+[2][ ]name+:name_2:name_3:name_4", ColumnParseError),
    ("+[2][ ]na+me:name_2:name_3:name_4", ColumnParseError),
    ("+[2][ ]+name:name_2:name_3:name_4", ColumnParseError),
    ("+[2][a]name*:name_2:name_3:name_4", ColumnParseError),
    ("+[2][a]na*me:name_2:name_3:name_4", ColumnParseError),
    ("+[2][a]*name:name_2:name_3:name_4", ColumnParseError),
    ("+[2][a]name/:name_2:name_3:name_4", ColumnParseError),
    ("+[2][a]na/me:name_2:name_3:name_4", ColumnParseError),
    ("+[2][a]/name:name_2:name_3:name_4", ColumnParseError),
    ("+[2][a]name :name_2:name_3:name_4", ColumnParseError),
    ("+[2][a]na me:name_2:name_3:name_4", ColumnParseError),
    ("+[2][a] name:name_2:name_3:name_4", ColumnParseError),
    ("+[2][a]name+:name_2:name_3:name_4", ColumnParseError),
    ("+[2][a]na+me:name_2:name_3:name_4", ColumnParseError),
    ("+[2][a]+name:name_2:name_3:name_4", ColumnParseError),
    ("+[2][10]name*:name_2:name_3:name_4", ColumnParseError),
    ("+[2][10]na*me:name_2:name_3:name_4", ColumnParseError),
    ("+[2][10]*name:name_2:name_3:name_4", ColumnParseError),
    ("+[2][10]name/:name_2:name_3:name_4", ColumnParseError),
    ("+[2][10]na/me:name_2:name_3:name_4", ColumnParseError),
    ("+[2][10]/name:name_2:name_3:name_4", ColumnParseError),
    ("+[2][10]name :name_2:name_3:name_4", ColumnParseError),
    ("+[2][10]na me:name_2:name_3:name_4", ColumnParseError),
    ("+[2][10] name:name_2:name_3:name_4", ColumnParseError),
    ("+[2][10]name+:name_2:name_3:name_4", ColumnParseError),
    ("+[2][10]na+me:name_2:name_3:name_4", ColumnParseError),
    ("+[2][10]+name:name_2:name_3:name_4", ColumnParseError),
    ("name*:name_2:name_3:name_4", ColumnParseError),
    ("na*me:name_2:name_3:name_4", ColumnParseError),
    ("*name:name_2:name_3:name_4", ColumnParseError),
    ("name/:name_2:name_3:name_4", ColumnParseError),
    ("na/me:name_2:name_3:name_4", ColumnParseError),
    ("/name:name_2:name_3:name_4", ColumnParseError),
    ("name :name_2:name_3:name_4", ColumnParseError),
    ("na me:name_2:name_3:name_4", ColumnParseError),
    (" name:name_2:name_3:name_4", ColumnParseError),
    ("name+:name_2:name_3:name_4", ColumnParseError),
    ("na+me:name_2:name_3:name_4", ColumnParseError),
    ("+name:name_2:name_3:name_4", ColumnParseError),
    ("[2]name*:name_2:name_3:name_4", ColumnParseError),
    ("[2]na*me:name_2:name_3:name_4", ColumnParseError),
    ("[2]*name:name_2:name_3:name_4", ColumnParseError),
    ("[2]name/:name_2:name_3:name_4", ColumnParseError),
    ("[2]na/me:name_2:name_3:name_4", ColumnParseError),
    ("[2]/name:name_2:name_3:name_4", ColumnParseError),
    ("[2]name :name_2:name_3:name_4", ColumnParseError),
    ("[2]na me:name_2:name_3:name_4", ColumnParseError),
    ("[2] name:name_2:name_3:name_4", ColumnParseError),
    ("[2]name+:name_2:name_3:name_4", ColumnParseError),
    ("[2]na+me:name_2:name_3:name_4", ColumnParseError),
    ("[2]+name:name_2:name_3:name_4", ColumnParseError),
    ("[]name*:name_2:name_3:name_4", ColumnParseError),
    ("[]na*me:name_2:name_3:name_4", ColumnParseError),
    ("[]*name:name_2:name_3:name_4", ColumnParseError),
    ("[]name/:name_2:name_3:name_4", ColumnParseError),
    ("[]na/me:name_2:name_3:name_4", ColumnParseError),
    ("[]/name:name_2:name_3:name_4", ColumnParseError),
    ("[]name :name_2:name_3:name_4", ColumnParseError),
    ("[]na me:name_2:name_3:name_4", ColumnParseError),
    ("[] name:name_2:name_3:name_4", ColumnParseError),
    ("[]name+:name_2:name_3:name_4", ColumnParseError),
    ("[]na+me:name_2:name_3:name_4", ColumnParseError),
    ("[]+name:name_2:name_3:name_4", ColumnParseError),
    ("[-1]name*:name_2:name_3:name_4", ColumnParseError),
    ("[-1]na*me:name_2:name_3:name_4", ColumnParseError),
    ("[-1]*name:name_2:name_3:name_4", ColumnParseError),
    ("[-1]name/:name_2:name_3:name_4", ColumnParseError),
    ("[-1]na/me:name_2:name_3:name_4", ColumnParseError),
    ("[-1]/name:name_2:name_3:name_4", ColumnParseError),
    ("[-1]name :name_2:name_3:name_4", ColumnParseError),
    ("[-1]na me:name_2:name_3:name_4", ColumnParseError),
    ("[-1] name:name_2:name_3:name_4", ColumnParseError),
    ("[-1]name+:name_2:name_3:name_4", ColumnParseError),
    ("[-1]na+me:name_2:name_3:name_4", ColumnParseError),
    ("[-1]+name:name_2:name_3:name_4", ColumnParseError),
    ("[abc]name*:name_2:name_3:name_4", ColumnParseError),
    ("[abc]na*me:name_2:name_3:name_4", ColumnParseError),
    ("[abc]*name:name_2:name_3:name_4", ColumnParseError),
    ("[abc]name/:name_2:name_3:name_4", ColumnParseError),
    ("[abc]na/me:name_2:name_3:name_4", ColumnParseError),
    ("[abc]/name:name_2:name_3:name_4", ColumnParseError),
    ("[abc]name :name_2:name_3:name_4", ColumnParseError),
    ("[abc]na me:name_2:name_3:name_4", ColumnParseError),
    ("[abc] name:name_2:name_3:name_4", ColumnParseError),
    ("[abc]name+:name_2:name_3:name_4", ColumnParseError),
    ("[abc]na+me:name_2:name_3:name_4", ColumnParseError),
    ("[abc]+name:name_2:name_3:name_4", ColumnParseError),
    ("[29a]name*:name_2:name_3:name_4", ColumnParseError),
    ("[29a]na*me:name_2:name_3:name_4", ColumnParseError),
    ("[29a]*name:name_2:name_3:name_4", ColumnParseError),
    ("[29a]name/:name_2:name_3:name_4", ColumnParseError),
    ("[29a]na/me:name_2:name_3:name_4", ColumnParseError),
    ("[29a]/name:name_2:name_3:name_4", ColumnParseError),
    ("[29a]name :name_2:name_3:name_4", ColumnParseError),
    ("[29a]na me:name_2:name_3:name_4", ColumnParseError),
    ("[29a] name:name_2:name_3:name_4", ColumnParseError),
    ("[29a]name+:name_2:name_3:name_4", ColumnParseError),
    ("[29a]na+me:name_2:name_3:name_4", ColumnParseError),
    ("[29a]+name:name_2:name_3:name_4", ColumnParseError),
    ("[2name*:name_2:name_3:name_4", ColumnParseError),
    ("[2na*me:name_2:name_3:name_4", ColumnParseError),
    ("[2*name:name_2:name_3:name_4", ColumnParseError),
    ("[2name/:name_2:name_3:name_4", ColumnParseError),
    ("[2na/me:name_2:name_3:name_4", ColumnParseError),
    ("[2/name:name_2:name_3:name_4", ColumnParseError),
    ("[2name :name_2:name_3:name_4", ColumnParseError),
    ("[2na me:name_2:name_3:name_4", ColumnParseError),
    ("[2 name:name_2:name_3:name_4", ColumnParseError),
    ("[2name+:name_2:name_3:name_4", ColumnParseError),
    ("[2na+me:name_2:name_3:name_4", ColumnParseError),
    ("[2+name:name_2:name_3:name_4", ColumnParseError),
    ("2]name*:name_2:name_3:name_4", ColumnParseError),
    ("2]na*me:name_2:name_3:name_4", ColumnParseError),
    ("2]*name:name_2:name_3:name_4", ColumnParseError),
    ("2]name/:name_2:name_3:name_4", ColumnParseError),
    ("2]na/me:name_2:name_3:name_4", ColumnParseError),
    ("2]/name:name_2:name_3:name_4", ColumnParseError),
    ("2]name :name_2:name_3:name_4", ColumnParseError),
    ("2]na me:name_2:name_3:name_4", ColumnParseError),
    ("2] name:name_2:name_3:name_4", ColumnParseError),
    ("2]name+:name_2:name_3:name_4", ColumnParseError),
    ("2]na+me:name_2:name_3:name_4", ColumnParseError),
    ("2]+name:name_2:name_3:name_4", ColumnParseError),
    ("[+]name*:name_2:name_3:name_4", ColumnParseError),
    ("[+]na*me:name_2:name_3:name_4", ColumnParseError),
    ("[+]*name:name_2:name_3:name_4", ColumnParseError),
    ("[+]name/:name_2:name_3:name_4", ColumnParseError),
    ("[+]na/me:name_2:name_3:name_4", ColumnParseError),
    ("[+]/name:name_2:name_3:name_4", ColumnParseError),
    ("[+]name :name_2:name_3:name_4", ColumnParseError),
    ("[+]na me:name_2:name_3:name_4", ColumnParseError),
    ("[+] name:name_2:name_3:name_4", ColumnParseError),
    ("[+]name+:name_2:name_3:name_4", ColumnParseError),
    ("[+]na+me:name_2:name_3:name_4", ColumnParseError),
    ("[+]+name:name_2:name_3:name_4", ColumnParseError),
    ("[name*:name_2:name_3:name_4", ColumnParseError),
    ("[na*me:name_2:name_3:name_4", ColumnParseError),
    ("[*name:name_2:name_3:name_4", ColumnParseError),
    ("[name/:name_2:name_3:name_4", ColumnParseError),
    ("[na/me:name_2:name_3:name_4", ColumnParseError),
    ("[/name:name_2:name_3:name_4", ColumnParseError),
    ("[name :name_2:name_3:name_4", ColumnParseError),
    ("[na me:name_2:name_3:name_4", ColumnParseError),
    ("[ name:name_2:name_3:name_4", ColumnParseError),
    ("[name+:name_2:name_3:name_4", ColumnParseError),
    ("[na+me:name_2:name_3:name_4", ColumnParseError),
    ("[+name:name_2:name_3:name_4", ColumnParseError),
    ("]name*:name_2:name_3:name_4", ColumnParseError),
    ("]na*me:name_2:name_3:name_4", ColumnParseError),
    ("]*name:name_2:name_3:name_4", ColumnParseError),
    ("]name/:name_2:name_3:name_4", ColumnParseError),
    ("]na/me:name_2:name_3:name_4", ColumnParseError),
    ("]/name:name_2:name_3:name_4", ColumnParseError),
    ("]name :name_2:name_3:name_4", ColumnParseError),
    ("]na me:name_2:name_3:name_4", ColumnParseError),
    ("] name:name_2:name_3:name_4", ColumnParseError),
    ("]name+:name_2:name_3:name_4", ColumnParseError),
    ("]na+me:name_2:name_3:name_4", ColumnParseError),
    ("]+name:name_2:name_3:name_4", ColumnParseError),
    ("[ ]name*:name_2:name_3:name_4", ColumnParseError),
    ("[ ]na*me:name_2:name_3:name_4", ColumnParseError),
    ("[ ]*name:name_2:name_3:name_4", ColumnParseError),
    ("[ ]name/:name_2:name_3:name_4", ColumnParseError),
    ("[ ]na/me:name_2:name_3:name_4", ColumnParseError),
    ("[ ]/name:name_2:name_3:name_4", ColumnParseError),
    ("[ ]name :name_2:name_3:name_4", ColumnParseError),
    ("[ ]na me:name_2:name_3:name_4", ColumnParseError),
    ("[ ] name:name_2:name_3:name_4", ColumnParseError),
    ("[ ]name+:name_2:name_3:name_4", ColumnParseError),
    ("[ ]na+me:name_2:name_3:name_4", ColumnParseError),
    ("[ ]+name:name_2:name_3:name_4", ColumnParseError),
    ("[2][name*:name_2:name_3:name_4", ColumnParseError),
    ("[2][na*me:name_2:name_3:name_4", ColumnParseError),
    ("[2][*name:name_2:name_3:name_4", ColumnParseError),
    ("[2][name/:name_2:name_3:name_4", ColumnParseError),
    ("[2][na/me:name_2:name_3:name_4", ColumnParseError),
    ("[2][/name:name_2:name_3:name_4", ColumnParseError),
    ("[2][name :name_2:name_3:name_4", ColumnParseError),
    ("[2][na me:name_2:name_3:name_4", ColumnParseError),
    ("[2][ name:name_2:name_3:name_4", ColumnParseError),
    ("[2][name+:name_2:name_3:name_4", ColumnParseError),
    ("[2][na+me:name_2:name_3:name_4", ColumnParseError),
    ("[2][+name:name_2:name_3:name_4", ColumnParseError),
    ("[2]]name*:name_2:name_3:name_4", ColumnParseError),
    ("[2]]na*me:name_2:name_3:name_4", ColumnParseError),
    ("[2]]*name:name_2:name_3:name_4", ColumnParseError),
    ("[2]]name/:name_2:name_3:name_4", ColumnParseError),
    ("[2]]na/me:name_2:name_3:name_4", ColumnParseError),
    ("[2]]/name:name_2:name_3:name_4", ColumnParseError),
    ("[2]]name :name_2:name_3:name_4", ColumnParseError),
    ("[2]]na me:name_2:name_3:name_4", ColumnParseError),
    ("[2]] name:name_2:name_3:name_4", ColumnParseError),
    ("[2]]name+:name_2:name_3:name_4", ColumnParseError),
    ("[2]]na+me:name_2:name_3:name_4", ColumnParseError),
    ("[2]]+name:name_2:name_3:name_4", ColumnParseError),
    ("[2][]name*:name_2:name_3:name_4", ColumnParseError),
    ("[2][]na*me:name_2:name_3:name_4", ColumnParseError),
    ("[2][]*name:name_2:name_3:name_4", ColumnParseError),
    ("[2][]name/:name_2:name_3:name_4", ColumnParseError),
    ("[2][]na/me:name_2:name_3:name_4", ColumnParseError),
    ("[2][]/name:name_2:name_3:name_4", ColumnParseError),
    ("[2][]name :name_2:name_3:name_4", ColumnParseError),
    ("[2][]na me:name_2:name_3:name_4", ColumnParseError),
    ("[2][] name:name_2:name_3:name_4", ColumnParseError),
    ("[2][]name+:name_2:name_3:name_4", ColumnParseError),
    ("[2][]na+me:name_2:name_3:name_4", ColumnParseError),
    ("[2][]+name:name_2:name_3:name_4", ColumnParseError),
    ("[2][ ]name*:name_2:name_3:name_4", ColumnParseError),
    ("[2][ ]na*me:name_2:name_3:name_4", ColumnParseError),
    ("[2][ ]*name:name_2:name_3:name_4", ColumnParseError),
    ("[2][ ]name/:name_2:name_3:name_4", ColumnParseError),
    ("[2][ ]na/me:name_2:name_3:name_4", ColumnParseError),
    ("[2][ ]/name:name_2:name_3:name_4", ColumnParseError),
    ("[2][ ]name :name_2:name_3:name_4", ColumnParseError),
    ("[2][ ]na me:name_2:name_3:name_4", ColumnParseError),
    ("[2][ ] name:name_2:name_3:name_4", ColumnParseError),
    ("[2][ ]name+:name_2:name_3:name_4", ColumnParseError),
    ("[2][ ]na+me:name_2:name_3:name_4", ColumnParseError),
    ("[2][ ]+name:name_2:name_3:name_4", ColumnParseError),
    ("[2][a]name*:name_2:name_3:name_4", ColumnParseError),
    ("[2][a]na*me:name_2:name_3:name_4", ColumnParseError),
    ("[2][a]*name:name_2:name_3:name_4", ColumnParseError),
    ("[2][a]name/:name_2:name_3:name_4", ColumnParseError),
    ("[2][a]na/me:name_2:name_3:name_4", ColumnParseError),
    ("[2][a]/name:name_2:name_3:name_4", ColumnParseError),
    ("[2][a]name :name_2:name_3:name_4", ColumnParseError),
    ("[2][a]na me:name_2:name_3:name_4", ColumnParseError),
    ("[2][a] name:name_2:name_3:name_4", ColumnParseError),
    ("[2][a]name+:name_2:name_3:name_4", ColumnParseError),
    ("[2][a]na+me:name_2:name_3:name_4", ColumnParseError),
    ("[2][a]+name:name_2:name_3:name_4", ColumnParseError),
    ("[2][10]name*:name_2:name_3:name_4", ColumnParseError),
    ("[2][10]na*me:name_2:name_3:name_4", ColumnParseError),
    ("[2][10]*name:name_2:name_3:name_4", ColumnParseError),
    ("[2][10]name/:name_2:name_3:name_4", ColumnParseError),
    ("[2][10]na/me:name_2:name_3:name_4", ColumnParseError),
    ("[2][10]/name:name_2:name_3:name_4", ColumnParseError),
    ("[2][10]name :name_2:name_3:name_4", ColumnParseError),
    ("[2][10]na me:name_2:name_3:name_4", ColumnParseError),
    ("[2][10] name:name_2:name_3:name_4", ColumnParseError),
    ("[2][10]name+:name_2:name_3:name_4", ColumnParseError),
    ("[2][10]na+me:name_2:name_3:name_4", ColumnParseError),
    ("[2][10]+name:name_2:name_3:name_4", ColumnParseError),
    ("name:name_2:name_3:name_4", ColumnParseError),
    ("+name:name_2:name_3:name_4", ColumnParseError),
    ("[2]name:name_2:name_3:name_4", ColumnParseError),
    ("+[2]name:name_2:name_3:name_4", ColumnParseError),
]
