site_name: CRIPT Excel Uploader Documentation

repo_url: https://github.com/C-Accel-CRIPT/cript-excel-uploader
repo_name: C-Accel-CRIPT/cript-excel-uploader

nav:
  - Quick Start: index.md
  - Filling Out First Screen: "filling_out_first_screen.md"
  - Structure of Excel Sheets: "excel_rows.md"
  - Individual Excel Sheets: "individual_sheets.md"

theme:
  name: material
  palette:
    primary: deep purple
    accent: deep purple
  icon:
    repo: fontawesome/brands/github

extra_css:
  - stylesheets/extra.css

plugins:
  - search
  - mkdocs-jupyter
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          selection:
            docstring_style: "restructured-text"
          rendering:
            show_source: true
            heading_level: 3

markdown_extensions:
  - toc:
      baselevel: 1
      permalink: True
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
