site_name: CRIPT Excel Uploader Documentation

repo_url: https://github.com/C-Accel-CRIPT/cript-excel-uploaders
repo_name: C-Accel-CRIPT/cript-excel-uploader

theme:
  name: material
  palette:
    primary: deep purple
    accent: deep purple
  icon:
    repo: fontawesome/brands/github

plugins:
  - search
  - mkdocs-jupyter
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          selection:
            docstring_style: "restructured-text"
          rendering:
            show_source: true
            heading_level: 3

nav:
  - Home: index.md

markdown_extensions:
  - toc:
      baselevel: 1
      permalink: True
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences