name: Compile GUI for Ubuntu
# run this job manually
on: workflow_dispatch
#  push:
#    branches:
#      - develop_action_compiling_gui

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # used to check out different branches
      - uses: actions/checkout@v3
#        with:
#          # checkout my specific branch
#          ref: master
      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: pip install dependencies
        run: pip install -r requirements_dev.txt
      - name: compile GUI for ubuntu
        working-directory: src/
        run: python -m eel gui_main.py web/ --onefile --noconsole --name excel_uploader_linux --icon=/assets/logo_condensed.ico

      # save compiled GUI
      - uses: actions/upload-artifact@v3
        with:
          # artifact name
          name: CRIPT Excel Uploader Linux Zip
          path: src/dist/
          if-no-files-found: error
          retention-days: 10
